
---

# ***`Working With CSV Files`***

### **Import pandas**

In [2]:
import pandas as pd

### **Load `local csv` data**

In [4]:
df = pd.read_csv("./data/aug_train.csv")
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### **`index_col` paramerter**

- Sometimes you need to set some column from your data as index.

In [13]:
df = pd.read_csv("./data/aug_train.csv",index_col="enrollee_id")
df.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### **`header` paramerter**

- Sometimes you see that your data column names become first row of data and your columns names are like `Unnamed: 0`,`Unnamed: 1` etc.

- If we want our first row of data to be header then we need to use `header=1` parameter.

```python
df = pd.read_csv("test.csv",header=1)
df.head()
```

### **`usecols` paramerter**

- Sometimes you need only few columns for analysis.
- You can specify them while importing data and rest of the columns will be removed.

In [15]:
df = pd.read_csv("./data/aug_train.csv",usecols=["enrollee_id","gender","education_level"])
df.head()

   enrollee_id gender education_level
0         8949   Male        Graduate
1        29725   Male        Graduate
2        11561    NaN        Graduate
3        33241    NaN        Graduate
4          666   Male         Masters

### **`skiprows/nrows` paramerter**

- Sometimes you need remove few rows for analysis.
- You can specify them while importing data and that rows will be removed from rest of the data.

In [ ]:
# df = pd.read_csv("./data/aug_train.csv",skiprows=[0,1])
df = pd.read_csv("./data/aug_train.csv",nrows=10) # specify number of rows
df.head()

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0

### **`encoding` paramerter**


- Sometimes you need to declare encoding of your data. 
- You need to find the encoding.

In [20]:
df = pd.read_csv("./data/zomato.csv",encoding="latin-1") 
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

### **`on_bad_lines='skip'` skip bad lines**

- Sometimes your data contain somes ***rows*** that are disordered, ike your data has 10 rows but some rows has 12 values in this case use `on_bad_lines='skip'`

In [23]:
df = pd.read_csv("./data/BX-Books.csv", sep=";", encoding="latin-1", on_bad_lines='skip')
df.head()

  isbn,book_title,book_author,year_of_publication,publisher
0  195153448,Classical Mythology,Mark P. O. Morfo...
1  2005018,Clara Callan,Richard Bruce Wright,2001...
2  60973129,Decision in Normandy,Carlo D'Este,199...
3  374157065,Flu: The Story of the Great Influenz...
4  399135782,The Kitchen God's Wife,Amy Tan,1991,...

### **`parse_dates=['column_name']`Handling Dates**
- You can change datatype of datetime columns on importing the dataset using `parse_dates=['column_name']`.

In [26]:
df = pd.read_csv(r"E:\Data Science Materials\Codanics\practice_dataset\payments.csv",parse_dates=['paymentDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerNumber  273 non-null    int64
 1   checkNumber     273 non-null    object
 2   paymentDate     273 non-null    datetime64[ns]
 3   amount          273 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 8.7+ KB

### **`na_values=['column_name']` parameter**

- We want to declare different types of `Null` values using 
-  `na_values=['column_name']`.

In [27]:
df = pd.read_csv("./data/aug_train.csv",nrows=10,na_values=['Male'])
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### **Load `csv` data from `URL`**

In [8]:
# Importing required libraries
import requests  # To make HTTP requests
from io import StringIO  # To handle in-memory text streams
import pandas as pd  # Importing pandas for data manipulation

# URL of the raw CSV file
url = "https://raw.githubusercontent.com/cs109/2014_data/refs/heads/master/countries.csv"

# Custom headers to mimic a browser request (some servers block default requests)
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}

# Sending a GET request to the URL with custom headers
req = requests.get(url, headers=headers)

# Converting the response text into a file-like object
data = StringIO(req.text)

# Reading the CSV data using pandas
df = pd.read_csv(data)  # Reading the CSV into a DataFrame

# Displaying the DataFrame
df.head()  # Shows the first 5 rows of the DataFrame

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

### **Load `local tsv` data**

- First we need to use `sep='\t'`.
- Second we need to `manually name the columns`.

In [12]:
import pandas as pd  # Importing pandas for data manipulation

# Reading the TSV data into a DataFrame
df = pd.read_csv("./data/movie.metadata.tsv", sep="\t", names=["serial_number", "name", "release_year", "rating", "votes", "genres"])

# Displaying the first 5 rows of the DataFrame
df.head()

,,,serial_number,name,release_year,rating,votes,genres
975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

### **`chunksize=n` Loading Huge Data in Chunks**

In [29]:
dfs = pd.read_csv("./data/aug_train.csv",chunksize=5000)

In [30]:
for chunk in dfs:
    print(chunk.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

---