
----


# ***`Fetching Data From an API`***

---


1. Create an api key

    ```bash
    THE_MOVIE_DATABASE_API_KEY="**************************"
    ```

- Visit this url

    ```bash
    https://api.themoviedb.org/3/movie/top_rated?api_key=***************&language=en-US&page=1
    ```

### **Import Libraries**

In [5]:
import os
import requests
import pandas as pd

### **Fetch Data From API**

- To fetch only `page 1` data.

In [ ]:

# Send a GET request to the API endpoint to fetch the top-rated movies
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=***********************&language=en-US&page=1")

# Convert the JSON response to a DataFrame and select specific columns
df = pd.DataFrame(response.json()["results"])[["id", "title", "overview", "release_date", "popularity", "vote_average", "vote_count"]]

# Display the first few rows of the DataFrame
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,51.885,8.7,27763
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,51.734,8.7,21069
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.478,8.6,12720
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,35.475,8.6,16173
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.388,8.5,8908

- To fetch `500` pages data.

In [ ]:
# Create an empty list to collect DataFrames
df_list = []

# Loop through pages 1 to 500 to fetch top-rated movies
for page_no in range(1, 501):
    # Send a GET request to the API endpoint for each page
    response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=***********************&language=en-US&page={page_no}")
    
    # Check if the request was successful
    if response.status_code == 200:
        # Convert the JSON response to a DataFrame and select specific columns
        temporary_df_movies = pd.DataFrame(response.json().get("results", []))[["id", "title", "overview", "release_date", "popularity", "vote_average", "vote_count"]]
        
        # Append the temporary DataFrame to the list
        df_list.append(temporary_df_movies)
    else:
        print(f"Failed to fetch data for page {page_no}, Status Code: {response.status_code}")

# Concatenate all DataFrames into a single DataFrame
the_df_movies = pd.concat(df_list, ignore_index=True)

# Display the final DataFrame
the_df_movies.head()

Failed to fetch data for page 220, Status Code: 404

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,51.885,8.7,27763
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,51.734,8.7,21069
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.478,8.6,12720
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,35.475,8.6,16173
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.388,8.5,8908

In [11]:
# shape of data
the_df_movies.shape

(9978, 7)

- In order to export data in csv use this command

    ```
    the_df_movies.to_csv("movies_data.csv")
    ```

---