
---

# ***`Handling Date and Time Variables`***

---

In [61]:
import datetime
import pandas as pd
import numpy as np
import seaborn as sns

In [40]:
date = pd.read_csv(r"https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv")
time = pd.read_csv(r"https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv")

In [41]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [42]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [43]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [44]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### **Working With Dates**

In [45]:
date['date'] = pd.to_datetime(date['date'])

In [46]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### **1. Extract Year**

In [47]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

#### **2. Extract Month**

In [48]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [49]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### **3. Extract Day**

In [50]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [51]:
# day of week
date['date_day_of_week'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [52]:
# day of week name
date['date_day_of_week_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [54]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_day_of_week_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### **4. Extract Week of the Year**

In [58]:
# Extract the week number from the 'date' column and create a new column 'date_week'
date['date_week'] = date['date'].dt.isocalendar().week

# Drop unnecessary columns ('product_id', 'city_id', 'orders') from the DataFrame
# Display the first few rows of the updated DataFrame
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

#### **5. Extract quarter of the Year**

In [59]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

#### **5. Extract Smester of the Year**

In [ ]:
# Create a new column 'semester' in the DataFrame 'date'
# Assign a value of 1 if 'quarter' is either 1 or 2 (indicating the first semester)
# Assign a value of 2 if 'quarter' is 3 or 4 (indicating the second semester)
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

#### **6. Time Elapsed Between 2 Dates**

In [62]:
today = datetime.datetime.today()

today

datetime.datetime(2025, 3, 1, 20, 56, 1, 331910)

In [63]:
today - date['date']

0     1908 days 20:56:01.331910
1     2390 days 20:56:01.331910
2     2321 days 20:56:01.331910
3     2023 days 20:56:01.331910
4     2246 days 20:56:01.331910
                 ...
995   2336 days 20:56:01.331910
996   2277 days 20:56:01.331910
997   2125 days 20:56:01.331910
998   2190 days 20:56:01.331910
999   1964 days 20:56:01.331910
Name: date, Length: 1000, dtype: timedelta64[ns]

In [64]:
(today - date['date']).dt.days

0      1908
1      2390
2      2321
3      2023
4      2246
       ...
995    2336
996    2277
997    2125
998    2190
999    1964
Name: date, Length: 1000, dtype: int64

In [66]:
from dateutil.relativedelta import relativedelta

# Calculate the number of months passed
months_passed = date['date'].apply(lambda x: relativedelta(today, x).years * 12 + relativedelta(today, x).months)

months_passed

0      62
1      78
2      76
3      66
4      73
       ..
995    76
996    74
997    69
998    71
999    64
Name: date, Length: 1000, dtype: int64

### **Time**

In [67]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [68]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [69]:
time['date'] = pd.to_datetime(time['date'])

In [70]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [71]:
time['hour']= time['date'].dt.hour
time['minute']= time['date'].dt.minute
time['second']= time['date'].dt.second

time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### **Extract the time part**

In [72]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,minute,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [74]:
# Create a new column with the datetime part
time['datetime'] = time['date']

# Calculate the time difference
today - time['datetime']

0     4094 days 20:06:01.331910
1     3958 days 21:16:01.331910
2     4444 days 20:35:01.331910
3     3746 days 20:25:01.331910
4     4143 days 21:45:01.331910
                 ...
995   4733 days 20:06:01.331910
996   4054 days 21:42:01.331910
997   4519 days 21:19:01.331910
998   4635 days 21:22:01.331910
999   3907 days 21:31:01.331910
Name: datetime, Length: 1000, dtype: timedelta64[ns]

In [75]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.537940e+08
1      3.420478e+08
2      3.840357e+08
3      3.237279e+08
4      3.580335e+08
           ...
995    4.090036e+08
996    3.503437e+08
997    3.905183e+08
998    4.005409e+08
999    3.376423e+08
Name: date, Length: 1000, dtype: float64

In [76]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      5.896566e+06
1      5.700796e+06
2      6.400595e+06
3      5.395465e+06
4      5.967225e+06
           ...
995    6.816726e+06
996    5.839062e+06
997    6.508639e+06
998    6.675682e+06
999    5.627371e+06
Name: date, Length: 1000, dtype: float64

In [77]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0       98276.100370
1       95013.267037
2      106676.583703
3       89924.417037
4       99453.750370
           ...
995    113612.100370
996     97317.700370
997    108477.317037
998    111261.367037
999     93789.517037
Name: date, Length: 1000, dtype: float64

---