
---

# 🔍 ***`Hyperparameter Tuning Using Optuna in Machine Learning for Data Science`***

---

## ✅ **What is Optuna?**  
📌 **Optuna** is a powerful, **automated hyperparameter optimization** framework designed for fast and efficient tuning of machine learning models.  

✅ Uses an **intelligent search algorithm** to find the best hyperparameters.  
✅ Faster than traditional methods like **GridSearchCV** and **RandomizedSearchCV**.  
✅ Offers a flexible API with support for various ML frameworks like **XGBoost**, **LightGBM**, **Scikit-learn**, and **PyTorch**.  
✅ Provides **visualization tools** to analyze the tuning process.

---

## ⚙️ **1. Key Features of Optuna**  

🔹 **Efficient Search Space Exploration** → Uses advanced optimization techniques like **TPE (Tree-structured Parzen Estimator)** and **CMA-ES**.  
🔹 **Early Stopping** → Stops trials that show poor results early to save time.  
🔹 **Pruning** → Discards underperforming models during training.  
🔹 **Asynchronous Optimization** → Enables parallel computing for faster results.  
🔹 **Dynamic Search Space** → Allows flexible parameter search during optimization.

---

## 📊 **2. How Does Optuna Work?**  

### 🔹 Step 1: Define the Objective Function
- The objective function takes a trial (search attempt) as input.  
- Inside this function, you define the model, hyperparameters, and evaluation metric.  

---

### 🔹 Step 2: Specify the Search Space
- Optuna automatically samples hyperparameters within specified ranges.  

---

### 🔹 Step 3: Optimize the Objective Function
- The `study.optimize()` method runs multiple trials to find the best hyperparameters.  

---

### 🔹 Step 4: Visualize and Analyze Results
- Optuna provides built-in tools to visualize the optimization process.


---

### **Key Terms to remember**



1. **Study**: A collection of trials that aim to find the optimal hyperparameters for a given objective function. It tracks the results of each trial and facilitates the decision-making process for hyperparameter tuning.  
   
   *Example*: `study = optuna.create_study(direction='minimize')`  
   ```python
   import optuna
   study = optuna.create_study(direction='minimize')
   ```

2. **Trial**: A single execution of the objective function using a specific set of hyperparameters. Each trial records the outcome, allowing for comparisons between different parameter configurations.  
   
   *Example*: `trial = study.enqueue_trial({})`  
   ```python
   trial = study.enqueue_trial({})
   ```

3. **Trial Parameters**: The hyperparameters that are sampled for a specific trial. These parameters guide the model training and influence the outcome of the objective function being optimized.  
   
   *Example*: `learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1)`  
   ```python
   learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1)
   ```

4. **Sampler**: An algorithm responsible for selecting hyperparameter values for each trial based on previous outcomes. It helps in efficiently exploring the parameter space to find optimal values.  
   
   *Example*: `sampler = optuna.samplers.TPESampler()`  
   ```python
   sampler = optuna.samplers.TPESampler()
   ```

5. **Objective Function**: The function that evaluates a set of hyperparameters by training a model and returning a performance metric. This function is called multiple times, once for each trial, to guide the optimization process.  
   
   *Example*: `def objective(trial): return some_model.train_and_evaluate(trial)`  
   ```python
   def objective(trial):
       return some_model.train_and_evaluate(trial)
   ```

---

## 🏹 **3. Implementing Optuna in Python**  

### 📁 **Dataset: Breast Cancer Classification (with RandomForest)**

In [43]:
!pip install optuna -q
!pip install optuna-integration -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 kB 3.7 MB/s eta 0:00:00

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import optuna

# Load Dataset
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Objective Function for Optuna
def objective(trial):
    # Define the hyperparameter search space
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 5)

    # Initialize Model with Suggested Parameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )

    # Train and Evaluate
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy  # Optuna will maximize this score

# Create Study and Optimize
study = optuna.create_study(direction='maximize')  # 'maximize' for accuracy
study.optimize(objective, n_trials=50)  # Number of trials for tuning

# Best Hyperparameters and Score
print("Best Parameters:", study.best_params)
print("Best Accuracy:", study.best_value)

[I 2025-03-15 09:51:54,322] A new study created in memory with name: no-name-7dee620b-a4d9-4dd8-b766-828c483988e5
[I 2025-03-15 09:51:54,757] Trial 0 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 297, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:54,994] Trial 1 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 157, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:55,189] Trial 2 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 134, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:55,485] Trial 3 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 193, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:55,666] Trial 4 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 126, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:55,861] Trial 5 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 125, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:56,118] Trial 6 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 171, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:56,550] Trial 7 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 202, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:56,749] Trial 8 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 99, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:57,175] Trial 9 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 199, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:57,698] Trial 10 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:58,122] Trial 11 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 279, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:58,517] Trial 12 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 265, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:58,628] Trial 13 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 64, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:58,999] Trial 14 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 238, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:59,367] Trial 15 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 240, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:59,594] Trial 16 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 161, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:51:59,958] Trial 17 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 235, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:00,051] Trial 18 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 53, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:00,202] Trial 19 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 90, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:00,433] Trial 20 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 148, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:00,649] Trial 21 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 139, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:00,818] Trial 22 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 106, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:01,101] Trial 23 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 182, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:01,429] Trial 24 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 214, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:01,683] Trial 25 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 163, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:01,809] Trial 26 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 77, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:01,995] Trial 27 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 122, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:02,339] Trial 28 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 223, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:02,635] Trial 29 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 184, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:02,870] Trial 30 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 149, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:03,063] Trial 31 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 112, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:03,288] Trial 32 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 137, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:03,701] Trial 33 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 265, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:04,007] Trial 34 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 195, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:04,216] Trial 35 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 127, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:04,476] Trial 36 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 170, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:04,633] Trial 37 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 90, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:04,871] Trial 38 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 151, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:05,264] Trial 39 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 253, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:05,587] Trial 40 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 210, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:06,022] Trial 41 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 294, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:06,227] Trial 42 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 122, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:06,437] Trial 43 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 131, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:06,613] Trial 44 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 110, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:06,913] Trial 45 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 194, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:07,174] Trial 46 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 163, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:07,710] Trial 47 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 289, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:08,018] Trial 48 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 142, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:08,255] Trial 49 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 95, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.

Best Parameters: {'n_estimators': 297, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}
Best Accuracy: 0.9707602339181286


---

## 📋 **4. Optuna Search Space Techniques**  

Optuna offers flexible search spaces with various data types:  

### 🔹 **Integer Search Space** (`suggest_int()`)
- Used for tuning hyperparameters that require **integer values**.

In [ ]:
trial.suggest_int('max_depth', 3, 20)



---

### 🔹 **Float Search Space** (`suggest_float()`)
- Used for tuning **continuous values** like **learning rates**.

In [ ]:
trial.suggest_float('learning_rate', 0.01, 0.3, log=True)


---

### 🔹 **Categorical Search Space** (`suggest_categorical()`)
- Used for tuning **discrete options** like kernels, optimizers, or functions.

In [ ]:
trial.suggest_categorical('criterion', ['gini', 'entropy'])


---

### 🔹 **Logarithmic Search Space** (`suggest_loguniform()`)
- Useful for values that scale exponentially.  
```python

In [ ]:
trial.suggest_float('alpha', 1e-5, 1e-1, log=True)


---

## 📊 **5. Visualizing Optuna Results**  

Optuna includes several powerful visualization tools:

### 🔹 **1. Visualizing Optimization History**

In [3]:
import optuna.visualization as vis

# Plot Optimization History
vis.plot_optimization_history(study)


---

### 🔹 **2. Visualizing Hyperparameter Importance**

In [4]:
vis.plot_param_importances(study)


---

### 🔹 **3. Visualizing Hyperparameter Relationships**

In [5]:
vis.plot_parallel_coordinate(study)


---

## 🔥 **6. Advanced Optuna Features**  

### 🔹 **1. Early Stopping with `Pruners`**
- Optuna automatically stops poorly performing trials to save time.  
- Common pruning strategies include:
  - **`MedianPruner`** (default) → Stops trials with results below the median.  
  - **`ThresholdPruner`** → Stops trials below a set threshold.  

**Example: Using a Pruner in Optuna**

In [6]:
pruner = optuna.pruners.MedianPruner(n_warmup_steps=10)

study = optuna.create_study(direction='maximize', pruner=pruner)
study.optimize(objective, n_trials=100)

[I 2025-03-15 09:52:12,789] A new study created in memory with name: no-name-e3566aff-809f-4ff4-966a-1653e730f5b4
[I 2025-03-15 09:52:13,068] Trial 0 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 195, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:13,225] Trial 1 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 102, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:13,589] Trial 2 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 248, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:13,833] Trial 3 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 162, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:14,177] Trial 4 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 234, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:14,371] Trial 5 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 120, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:14,636] Trial 6 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 177, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:15,015] Trial 7 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 249, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:15,393] Trial 8 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 252, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:15,762] Trial 9 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 246, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:15,867] Trial 10 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 66, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:15,957] Trial 11 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 55, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:16,250] Trial 12 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 187, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:16,429] Trial 13 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 115, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:16,629] Trial 14 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 127, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:17,076] Trial 15 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:17,219] Trial 16 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 87, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:17,486] Trial 17 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 153, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:17,818] Trial 18 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 218, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:18,132] Trial 19 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 204, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:18,288] Trial 20 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 91, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:18,817] Trial 21 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:19,382] Trial 22 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 274, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:19,837] Trial 23 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 202, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:20,069] Trial 24 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 148, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:20,484] Trial 25 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 268, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:20,824] Trial 26 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 225, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:21,125] Trial 27 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 196, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:21,356] Trial 28 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 142, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:21,628] Trial 29 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 177, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:21,869] Trial 30 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 167, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:22,024] Trial 31 finished with value: 0.9590643274853801 and parameters: {'n_estimators': 94, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:22,376] Trial 32 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 217, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:22,634] Trial 33 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 161, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:22,818] Trial 34 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 110, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:23,032] Trial 35 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 131, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:23,403] Trial 36 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 236, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:23,837] Trial 37 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 276, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:24,118] Trial 38 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 185, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:24,511] Trial 39 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 253, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:24,633] Trial 40 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 69, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:24,996] Trial 41 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 234, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:25,387] Trial 42 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 255, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:25,720] Trial 43 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 210, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:26,091] Trial 44 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 238, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:26,381] Trial 45 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 188, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:26,841] Trial 46 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 286, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:27,200] Trial 47 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 228, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:27,459] Trial 48 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 168, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:27,865] Trial 49 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 264, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:28,036] Trial 50 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 103, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:28,255] Trial 51 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 135, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:28,642] Trial 52 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 245, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:28,829] Trial 53 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 120, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:29,080] Trial 54 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 156, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:29,204] Trial 55 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 70, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:29,516] Trial 56 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 198, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:29,800] Trial 57 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 177, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:30,312] Trial 58 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 218, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:31,435] Trial 59 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 187, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:31,610] Trial 60 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 50, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:32,458] Trial 61 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 246, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:33,414] Trial 62 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 262, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:34,222] Trial 63 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 213, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:34,452] Trial 64 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 146, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:34,595] Trial 65 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 80, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:35,420] Trial 66 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 227, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:36,030] Trial 67 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 207, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:36,818] Trial 68 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 275, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:37,220] Trial 69 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 282, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:37,819] Trial 70 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 245, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:38,615] Trial 71 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 256, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:39,287] Trial 72 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 238, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:39,723] Trial 73 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 290, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:40,086] Trial 74 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 193, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:40,395] Trial 75 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 174, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:40,781] Trial 76 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 251, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:41,135] Trial 77 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 222, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:41,887] Trial 78 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 262, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:42,526] Trial 79 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 230, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:43,143] Trial 80 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 268, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:43,516] Trial 81 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 239, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:43,776] Trial 82 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 161, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:44,283] Trial 83 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 249, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:44,689] Trial 84 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 139, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:45,593] Trial 85 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 269, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:46,240] Trial 86 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 257, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.


---

### 🔹 **2. Saving and Loading Optuna Studies**
- Save results to a database for future analysis.  

**Saving the Study:**

In [7]:
study = optuna.create_study(study_name='rf_study', direction='maximize', storage='sqlite:///optuna_study.db')
study.optimize(objective, n_trials=50)

[I 2025-03-15 09:52:51,797] A new study created in RDB with name: rf_study
[I 2025-03-15 09:52:52,326] Trial 0 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 293, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:52,567] Trial 1 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 54, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:53,081] Trial 2 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 232, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:53,443] Trial 3 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 148, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:53,643] Trial 4 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 56, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:54,120] Trial 5 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 179, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:54,692] Trial 6 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 168, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:54,933] Trial 7 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 56, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:55,221] Trial 8 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 73, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:55,803] Trial 9 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 290, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:56,512] Trial 10 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 298, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:56,910] Trial 11 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 116, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:57,672] Trial 12 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 231, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:58,102] Trial 13 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 232, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:58,345] Trial 14 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 108, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:58,804] Trial 15 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 267, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:59,217] Trial 16 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 103, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:52:59,916] Trial 17 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 199, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:00,406] Trial 18 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 138, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:00,905] Trial 19 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 260, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:01,280] Trial 20 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 202, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:01,712] Trial 21 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 240, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:02,094] Trial 22 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 209, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:02,571] Trial 23 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 274, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:03,211] Trial 24 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 247, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:03,901] Trial 25 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 216, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:04,894] Trial 26 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 281, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:05,630] Trial 27 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 178, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:05,947] Trial 28 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 87, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:06,316] Trial 29 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 127, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:06,626] Trial 30 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 154, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:06,780] Trial 31 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 51, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:07,154] Trial 32 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 153, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:07,898] Trial 33 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 257, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:08,298] Trial 34 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 185, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:08,528] Trial 35 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 93, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:08,751] Trial 36 finished with value: 0.9590643274853801 and parameters: {'n_estimators': 71, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:09,157] Trial 37 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 164, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:09,915] Trial 38 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 297, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:10,445] Trial 39 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 221, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:10,629] Trial 40 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 69, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:10,989] Trial 41 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 185, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:11,282] Trial 42 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 138, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:11,789] Trial 43 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 284, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:12,163] Trial 44 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 194, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:12,570] Trial 45 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 222, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:12,902] Trial 46 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 167, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:13,346] Trial 47 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 247, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:13,612] Trial 48 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 122, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:14,165] Trial 49 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 230, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.


**Loading the Study:**

In [8]:
study = optuna.load_study(study_name='rf_study', storage='sqlite:///optuna_study.db')

---

### 🔹 **3. Parallel Execution (Speeds Up Tuning)**
- Optuna supports parallel tuning to leverage multiple CPU cores.  

**Example: Parallel Execution with `n_jobs`**

In [9]:
study.optimize(objective, n_trials=100, n_jobs=4)

[I 2025-03-15 09:53:15,528] Trial 51 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 109, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:15,821] Trial 50 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 139, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:15,833] Trial 53 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 139, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:15,941] Trial 52 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 143, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:17,279] Trial 54 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 140, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:17,761] Trial 55 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 172, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:17,772] Trial 57 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 169, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:18,043] Trial 56 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 207, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:18,771] Trial 58 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 207, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:19,012] Trial 59 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 153, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:19,395] Trial 61 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 193, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:19,411] Trial 60 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 209, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:19,914] Trial 62 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 155, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,053] Trial 64 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 62, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,127] Trial 65 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 76, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,261] Trial 63 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 189, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,553] Trial 66 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 69, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,719] Trial 68 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:20,946] Trial 67 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 89, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:21,104] Trial 69 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 86, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:21,454] Trial 70 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 96, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:21,557] Trial 71 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 86, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:22,875] Trial 72 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 270, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:23,031] Trial 73 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 271, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:23,507] Trial 74 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 286, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:23,780] Trial 75 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 298, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:24,893] Trial 76 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 291, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:25,161] Trial 77 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 293, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:25,437] Trial 78 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 258, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:25,587] Trial 79 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 260, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:26,651] Trial 80 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 259, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:26,887] Trial 83 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 180, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:27,054] Trial 81 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 261, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:27,153] Trial 82 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 238, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:28,905] Trial 84 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 279, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:29,086] Trial 86 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 241, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:29,228] Trial 85 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 278, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:29,501] Trial 87 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 277, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:29,921] Trial 89 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 59, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:30,063] Trial 90 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 56, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:31,118] Trial 91 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 130, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:31,654] Trial 88 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:31,867] Trial 92 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 162, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:32,519] Trial 94 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 105, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:32,878] Trial 95 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:33,007] Trial 96 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 110, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:33,199] Trial 93 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:33,704] Trial 98 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 79, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:33,785] Trial 99 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 77, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:34,592] Trial 97 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 291, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:34,624] Trial 101 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 118, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:34,867] Trial 102 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 147, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:35,252] Trial 100 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 286, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:35,820] Trial 103 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 148, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:36,277] Trial 104 finished with value: 0.9649122807017544 and parameters: {'n_estimators': 226, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:36,285] Trial 106 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 130, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:36,321] Trial 105 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 198, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:37,011] Trial 107 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 177, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:37,752] Trial 109 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 179, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:37,844] Trial 108 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 216, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:38,255] Trial 110 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 251, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:38,269] Trial 111 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 162, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:39,298] Trial 112 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 159, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:39,911] Trial 116 finished with value: 0.9590643274853801 and parameters: {'n_estimators': 67, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:39,999] Trial 113 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 250, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:40,250] Trial 114 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 229, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:40,622] Trial 115 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 266, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:41,737] Trial 117 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 235, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:41,774] Trial 120 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 171, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:41,811] Trial 118 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 236, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:42,142] Trial 119 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 265, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:42,773] Trial 122 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 98, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:43,083] Trial 124 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 116, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:43,408] Trial 121 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 212, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:43,483] Trial 123 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 215, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:43,890] Trial 125 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 115, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:44,796] Trial 129 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 125, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:44,907] Trial 127 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 202, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:45,144] Trial 126 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 292, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:45,630] Trial 128 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 293, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:46,835] Trial 131 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 283, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:46,846] Trial 132 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 243, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:46,983] Trial 133 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:47,117] Trial 130 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 294, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:47,632] Trial 135 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 65, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:47,850] Trial 136 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 62, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.
[I 2025-03-15 09:53:48,199] Trial 138 finished with value: 0.9707602339181286 and parameters: {'n_estimators': 56, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9707602339181286.

---

## ⚠️ **7. Common Pitfalls in Hyperparameter Tuning**  

❌ **Overfitting** → Avoid too many trials or excessive tuning.  
❌ **Data Leakage** → Ensure your validation data is unseen by the model.  
❌ **Ignoring Feature Engineering** → Tuning won't fix poor feature quality.  
❌ **Ignoring Model Complexity** → Balance hyperparameter tuning with model simplicity.  

✅ **Best Practice:** Combine **Optuna** with **Cross-Validation** to enhance robustness.

---

## 📈 **8. Optuna vs Other Tuning Techniques**  

| Feature                | **Optuna**             | **GridSearchCV**      | **RandomizedSearchCV** |
|------------------------|------------------------|------------------------|-------------------------|
| **Search Efficiency**     | ✅ Highly efficient (fewer trials for better results) | ❗ Exhaustive (may require many trials) | ✅ Faster than GridSearch |
| **Dynamic Search Space**   | ✅ Supported             | ❌ Not supported         | ❌ Not supported          |
| **Early Stopping (Pruning)**| ✅ Supported             | ❌ Not supported         | ❌ Not supported          |
| **Parallel Execution**     | ✅ Easy to implement      | ❗ Requires manual handling | ❗ Requires manual handling |
| **Visualization Tools**    | ✅ Excellent visualization | ❌ Limited visualization | ❌ Limited visualization |


## 🚀 **9. Key Takeaways**  

✔️ **Optuna** is a powerful tool for fast, efficient hyperparameter tuning.  
✔️ Offers flexible search spaces with intelligent sampling techniques.  
✔️ Supports advanced features like **pruning**, **parallel execution**, and **visualization**.  
✔️ Great for tuning complex models like **XGBoost**, **LightGBM**, and **Neural Networks**.  

💡 **Pro Tip:** Use `study.best_trial` to inspect the best-performing trial’s details for deeper insights.

---


## ***`Futher Practing Optuna Code`***

In [10]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [14]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-03-15 10:30:22,231] A new study created in memory with name: no-name-4d5bfe55-0c5c-4d4f-901b-d444cca3f3c1
[I 2025-03-15 10:30:22,868] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 5}. Best is trial 0 with value: 0.7672253258845437.
[I 2025-03-15 10:30:23,223] Trial 1 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 0 with value: 0.7672253258845437.
[I 2025-03-15 10:30:23,929] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 186, 'max_depth': 8}. Best is trial 0 with value: 0.7672253258845437.
[I 2025-03-15 10:30:24,505] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 157, 'max_depth': 4}. Best is trial 0 with value: 0.7672253258845437.
[I 2025-03-15 10:30:24,743] Trial 4 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 62, 'max_depth': 8}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:24,985] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 17}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:25,566] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 157, 'max_depth': 6}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:25,898] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 87, 'max_depth': 9}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:26,142] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 62, 'max_depth': 15}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:26,823] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 13}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:27,261] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 20}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-03-15 10:30:27,695] Trial 11 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 114, 'max_depth': 19}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:28,191] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:28,409] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 53, 'max_depth': 20}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:28,883] Trial 14 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 125, 'max_depth': 11}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:29,318] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:29,904] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 9}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:30,588] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 136, 'max_depth': 13}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:30,874] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 74, 'max_depth': 7}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:31,299] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 17}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:31,584] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 74, 'max_depth': 14}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:32,014] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 18}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:32,564] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 19}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:32,955] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 99, 'max_depth': 18}. Best is trial 11 with value: 0.7783985102420856.
[I 2025-03-15 10:30:33,423] Trial 24 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:33,872] Trial 25 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 115, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:34,334] Trial 26 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:34,885] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:35,350] Trial 28 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 122, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:35,989] Trial 29 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 171, 'max_depth': 12}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:36,746] Trial 30 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 199, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:37,210] Trial 31 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:37,729] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 134, 'max_depth': 14}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:38,116] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:38,584] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 118, 'max_depth': 13}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:39,160] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 12}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:39,546] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:40,039] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 127, 'max_depth': 14}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:40,812] Trial 38 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 10}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:41,549] Trial 39 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 142, 'max_depth': 3}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:41,938] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 89, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:42,402] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 120, 'max_depth': 15}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:42,872] Trial 42 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:43,260] Trial 43 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 18}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:43,709] Trial 44 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:44,214] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 17}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:44,700] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 124, 'max_depth': 13}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:45,280] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 152, 'max_depth': 14}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:45,651] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 93, 'max_depth': 16}. Best is trial 24 with value: 0.7858472998137803.
[I 2025-03-15 10:30:46,055] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 19}. Best is trial 24 with value: 0.7858472998137803.

In [15]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7858472998137803
Best hyperparameters: {'n_estimators': 121, 'max_depth': 15}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76


### **Using RandomSampler in Optuna**

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [18]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-03-15 10:40:27,170] A new study created in memory with name: no-name-3f1111a9-9e15-47cf-a87f-e5c20c4e9cf4
[I 2025-03-15 10:40:27,524] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 95, 'max_depth': 7}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-03-15 10:40:28,222] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 185, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:28,564] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 93, 'max_depth': 11}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:29,276] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 192, 'max_depth': 9}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:29,878] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 159, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:30,493] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 166, 'max_depth': 19}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:30,931] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 14}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:31,536] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 164, 'max_depth': 11}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:31,874] Trial 8 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 90, 'max_depth': 6}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-03-15 10:40:32,583] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 190, 'max_depth': 10}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:33,111] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 140, 'max_depth': 15}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:33,449] Trial 11 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 98, 'max_depth': 4}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:34,104] Trial 12 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 189, 'max_depth': 5}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:34,347] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 64, 'max_depth': 17}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:34,898] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 15}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:35,492] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 14}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:35,839] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 91, 'max_depth': 12}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:36,620] Trial 17 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 141, 'max_depth': 8}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:38,197] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 166, 'max_depth': 10}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:39,063] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 15}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:39,664] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 143, 'max_depth': 4}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:40,268] Trial 21 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 114, 'max_depth': 3}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:40,603] Trial 22 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 58, 'max_depth': 3}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:41,199] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 92, 'max_depth': 20}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:42,125] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 18}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:42,566] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 20}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:43,044] Trial 26 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 144, 'max_depth': 3}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:43,275] Trial 27 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 67, 'max_depth': 3}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:43,957] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 13}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:44,212] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 64, 'max_depth': 9}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:45,174] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 163, 'max_depth': 7}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:45,768] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 119, 'max_depth': 8}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:46,320] Trial 32 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 9}. Best is trial 9 with value: 0.7746741154562384.
[I 2025-03-15 10:40:46,707] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 18}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:48,073] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 194, 'max_depth': 10}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:49,002] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 19}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:49,908] Trial 36 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 181, 'max_depth': 3}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:50,109] Trial 37 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 58, 'max_depth': 4}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:50,480] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 95, 'max_depth': 18}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:51,013] Trial 39 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 162, 'max_depth': 4}. Best is trial 33 with value: 0.7783985102420857.
[I 2025-03-15 10:40:51,502] Trial 40 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 16}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:51,944] Trial 41 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 127, 'max_depth': 4}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:52,550] Trial 42 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 171, 'max_depth': 6}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:53,042] Trial 43 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 133, 'max_depth': 15}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:53,607] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 159, 'max_depth': 6}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:54,344] Trial 45 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 200, 'max_depth': 11}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:54,955] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 165, 'max_depth': 17}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:55,180] Trial 47 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 12}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:55,798] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 13}. Best is trial 40 with value: 0.7802607076350093.
[I 2025-03-15 10:40:56,010] Trial 49 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 57, 'max_depth': 7}. Best is trial 40 with value: 0.7802607076350093.

In [19]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 129, 'max_depth': 16}

In [20]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74


### **Using GridSampler in Optuna**

In [21]:
# define a grid
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [22]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-03-15 10:43:33,466] A new study created in memory with name: no-name-69172a53-5948-4fe1-b6b8-f25e9df71e7a
[I 2025-03-15 10:43:33,817] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-03-15 10:43:34,375] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-03-15 10:43:34,565] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:34,938] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:35,323] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:35,511] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:36,027] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:36,579] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:37,135] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:37,878] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:38,617] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:39,352] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:40,038] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-03-15 10:43:40,218] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-03-15 10:43:40,592] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-03-15 10:43:40,787] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [23]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [24]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### **Optuna Visualizations**

In [25]:
# For visualizations
from optuna.visualization import (
    plot_optimization_history,
    plot_parallel_coordinate,
    plot_slice, plot_contour,
    plot_param_importances,
)

In [26]:
# 1. Optimization History
plot_optimization_history(study).show()

In [27]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [28]:
# 3. Slice Plot
plot_slice(study).show()

In [29]:
# 4. Contour Plot
plot_contour(study).show()

In [30]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

### **Optimizing Multiple ML Models**

In [31]:
# Importing the required libraries
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)
from sklearn.svm import SVC

In [32]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [33]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-03-15 11:13:12,435] A new study created in memory with name: no-name-49acff66-9a67-49d7-94ab-80de62132aa0
[I 2025-03-15 11:13:12,459] Trial 0 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 7.037910096107279, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:12,485] Trial 1 finished with value: 0.739292364990689 and parameters: {'classifier': 'SVM', 'C': 30.054551141351915, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:12,503] Trial 2 finished with value: 0.7243947858472999 and parameters: {'classifier': 'SVM', 'C': 1.4132200608481322, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:12,532] Trial 3 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.11049134624539234, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:12,551] Trial 4 finished with value: 0.7374301675977653 and parameters: {'classifier': 'SVM', 'C': 3.9613742997200174, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:14,694] Trial 5 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 117, 'learning_rate': 0.22961707244255616, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.7541899441340782.
[I 2025-03-15 11:13:15,289] Trial 6 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 59, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 6 with value: 0.7690875232774674.
[I 2025-03-15 11:13:15,787] Trial 7 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 77, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:16,644] Trial 8 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 137, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:17,997] Trial 9 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 269, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:19,904] Trial 10 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 214, 'learning_rate': 0.013427620216106103, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:20,120] Trial 11 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 58, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:20,327] Trial 12 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:20,685] Trial 13 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 113, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:20,903] Trial 14 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:21,475] Trial 15 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 162, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:22,755] Trial 16 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 98, 'learning_rate': 0.052978826473209874, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 7 with value: 0.7765363128491619.
[I 2025-03-15 11:13:23,574] Trial 17 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 220, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:24,242] Trial 18 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 222, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:24,871] Trial 19 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 209, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:26,945] Trial 20 finished with value: 0.7690875232774674 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 297, 'learning_rate': 0.01270027054514552, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:27,605] Trial 21 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 220, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:28,303] Trial 22 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 236, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:28,866] Trial 23 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 188, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:29,431] Trial 24 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 187, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:30,179] Trial 25 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 250, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:30,728] Trial 26 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 182, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:31,215] Trial 27 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 157, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:32,262] Trial 28 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 196, 'learning_rate': 0.29503437968594054, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:32,936] Trial 29 finished with value: 0.750465549348231 and parameters: {'classifier': 'RandomForest', 'n_estimators': 250, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 17 with value: 0.7802607076350093.
[I 2025-03-15 11:13:33,139] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 65.84696102000825, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:33,495] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 84.96141540432382, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:33,815] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 88.22255878864672, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:34,239] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.58190747966982, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:34,518] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 80.12714715754703, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:34,799] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 92.07908731639712, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,044] Trial 36 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 83.63101025814957, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,127] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 25.90887074910016, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,211] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 27.59868145163857, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,487] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.4059517946886, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,512] Trial 40 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 31.324019664149574, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,759] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.03685566049181, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:35,902] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 55.558305012348, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,030] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 44.04072885473177, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,081] Trial 44 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.416956317965932, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,224] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 50.90749913119692, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,405] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 56.44284134432986, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,430] Trial 47 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 14.059202953447663, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 30 with value: 0.7858472998137801.
[I 2025-03-15 11:13:36,452] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6578719254708089, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,474] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5188497019032811, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,500] Trial 50 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8954741165448787, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,523] Trial 51 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8195994648291947, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,546] Trial 52 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7791043982087428, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,569] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8002113510142254, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,591] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7801194237044113, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,613] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7440674570514103, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,635] Trial 56 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.6497515478922129, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:36,663] Trial 57 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.34003270332852176, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,389] Trial 58 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 299, 'learning_rate': 0.05807711599402453, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,414] Trial 59 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 1.3207845499466335, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,439] Trial 60 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1749534027273631, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,463] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.739662620188449, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,485] Trial 62 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32254743121980567, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,517] Trial 63 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.5870717662139833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,546] Trial 64 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.9143732552933616, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:41,575] Trial 65 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.3678924642948336, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,233] Trial 66 finished with value: 0.7337057728119181 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 130, 'learning_rate': 0.07091379101024835, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,257] Trial 67 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 0.38765786650214057, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,280] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2237400413205938, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,305] Trial 69 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.7371249846182515, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,331] Trial 70 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.9406777772034768, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,356] Trial 71 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6334571848825941, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,380] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8593292189041182, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,402] Trial 73 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5017073651697749, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,428] Trial 74 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.7521205476197281, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:43,457] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6989445720592505, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:48,275] Trial 76 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 280, 'learning_rate': 0.02905927557733376, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 48 with value: 0.7858472998137803.
[I 2025-03-15 11:13:48,325] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.172466574402788, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 77 with value: 0.7877094972067038.
[I 2025-03-15 11:13:48,395] Trial 78 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.18716429078879446, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 77 with value: 0.7877094972067038.
[I 2025-03-15 11:13:48,437] Trial 79 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14534064245883174, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 79 with value: 0.7895716945996275.

In [34]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.14534064245883174, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [35]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.754190,2025-03-15 11:13:12.436713,2025-03-15 11:13:12.459091,0 days 00:00:00.022378,7.037910,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.739292,2025-03-15 11:13:12.459871,2025-03-15 11:13:12.485177,0 days 00:00:00.025306,30.054551,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.724395,2025-03-15 11:13:12.485941,2025-03-15 11:13:12.503366,0 days 00:00:00.017425,1.413220,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.728119,2025-03-15 11:13:12.504060,2025-03-15 11:13:12.531976,0 days 00:00:00.027916,0.110491,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.737430,2025-03-15 11:13:12.532746,2025-03-15 11:13:12.551296,0 days 00:00:00.018550,3.961374,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2025-03-15 11:13:50.739266,2025-03-15 11:13:50.769671,0 days 00:00:00.030405,0.145306,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.789572,2025-03-15 11:13:50.773292,2025-03-15 11:13:50.820749,0 days 00:00:00.047457,0.140035,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2025-03-15 11:13:50.829868,2025-03-15 11:13:50.898308,0 days 00:00:00.068440,0.238834,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2025-03-15 11:13:50.909424,2025-03-15 11:13:50.989455,0 days 00:00:00.080031,0.139951,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.785847,2025-03-15 11:13:50.990648,2025-03-15 11:13:51.044611,0 days 00:00:00.053963,0.223695,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [36]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 71
RandomForest        20
GradientBoosting     9
Name: count, dtype: int64

In [37]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.747155
RandomForest        0.768901
SVM                 0.776772
Name: value, dtype: float64

In [38]:
# 1. Optimization History
plot_optimization_history(study).show()

In [39]:
# 3. Slice Plot
plot_slice(study).show()

In [40]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [44]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2025-03-15 11:17:30,249] A new study created in memory with name: no-name-04e3c84d-978c-42a6-9bca-8629e4c9bf0c

[0]	train-mlogloss:0.76434	eval-mlogloss:0.74152
[1]	train-mlogloss:0.59750	eval-mlogloss:0.56077
[2]	train-mlogloss:0.45597	eval-mlogloss:0.40612
[3]	train-mlogloss:0.35876	eval-mlogloss:0.29983
[4]	train-mlogloss:0.31452	eval-mlogloss:0.25280
[5]	train-mlogloss:0.27177	eval-mlogloss:0.20694
[6]	train-mlogloss:0.24924	eval-mlogloss:0.18167
[7]	train-mlogloss:0.24860	eval-mlogloss:0.17908
[8]	train-mlogloss:0.24841	eval-mlogloss:0.17994
[9]	train-mlogloss:0.24712	eval-mlogloss:0.17585
[10]	train-mlogloss:0.23737	eval-mlogloss:0.16357
[11]	train-mlogloss:0.23733	eval-mlogloss:0.16462
[12]	train-mlogloss:0.23717	eval-mlogloss:0.16474
[13]	train-mlogloss:0.23604	eval-mlogloss:0.16402
[14]	train-mlogloss:0.23583	eval-mlogloss:0.16486
[15]	train-mlogloss:0.23475	eval-mlogloss:0.16367
[16]	train-mlogloss:0.23402	eval-mlogloss:0.16319
[17]	train-mlogloss:0.23372	eval-mlogloss:0.16304
[18]	train-mlogloss:0.23417	eval-mlogloss:0.16323
[19]	train-mlogloss:0.23291	eval-mlogloss:0.16162
[20]	train-mlogloss:0.23300	eval-mlogloss:0.16177
[21]	train-mlogloss:0.23280	eval-mlogloss:0.16069
[22]	train-mlogloss:0.23167	eval-mlogloss:0.16037
[23]	train-mlogloss:0.23174	eval-mlogloss:0.16040
[24]	train-mlogloss:0.23138	eval-mlogloss:0.15989
[25]	train-mlogloss:0.22757	eval-mlogloss:0.15483
[26]	train-mlogloss:0.22731	eval-mlogloss:0.15478
[27]	train-mlogloss:0.22737	eval-mlogloss:0.15467
[28]	train-mlogloss:0.22733	eval-mlogloss:0.15490
[29]	train-mlogloss:0.22729	eval-mlogloss:0.15488
[30]	train-mlogloss:0.22650	eval-mlogloss:0.15463
[31]	train-mlogloss:0.22630	eval-mlogloss:0.15481
[32]	train-mlogloss:0.22529	eval-mlogloss:0.15435
[33]	train-mlogloss:0.22501	eval-mlogloss:0.15363
[34]	train-mlogloss:0.22482	eval-mlogloss:0.15286
[35]	train-mlogloss:0.22479	eval-mlogloss:0.15312
[36]	train-mlogloss:0.22495	eval-mlogloss:0.15360
[37]	train-mlogloss:0.22467	eval-mlogloss:0.15458
[38]	train-mlogloss:0.22460	eval-mlogloss:0.15476
[39]	train-mlogloss:0.22466	eval-mlogloss:0.15476
[40]	train-mlogloss:0.22363	eval-mlogloss:0.15437
[41]	train-mlogloss:0.22342	eval-mlogloss:0.15431
[42]	train-mlogloss:0.22287	eval-mlogloss:0.15209
[43]	train-mlogloss:0.22323	eval-mlogloss:0.15266
[44]	train-mlogloss:0.22307	eval-mlogloss:0.15244
[45]	train-mlogloss:0.22284	eval-mlogloss:0.15205
[46]	train-mlogloss:0.22243	eval-mlogloss:0.15105
[47]	train-mlogloss:0.22249	eval-mlogloss:0.15194
[48]	train-mlogloss:0.22221	eval-mlogloss:0.15187
[49]	train-mlogloss:0.22212	eval-mlogloss:0.15032
[50]	train-mlogloss:0.22011	eval-mlogloss:0.14665
[51]	train-mlogloss:0.22001	eval-mlogloss:0.14706
[52]	train-mlogloss:0.21999	eval-mlogloss:0.14705
[53]	train-mlogloss:0.22004	eval-mlogloss:0.14707
[54]	train-mlogloss:0.21977	eval-mlogloss:0.14649
[55]	train-mlogloss:0.21985	eval-mlogloss:0.14634
[56]	train-mlogloss:0.21974	eval-mlogloss:0.14602
[57]	train-mlogloss:0.21988	eval-mlogloss:0.14597
[58]	train-mlogloss:0.21985	eval-mlogloss:0.14612
[59]	train-mlogloss:0.21966	eval-mlogloss:0.14607
[60]	train-mlogloss:0.21952	eval-mlogloss:0.14613
[61]	train-mlogloss:0.21941	eval-mlogloss:0.14624
[62]	train-mlogloss:0.21957	eval-mlogloss:0.14668
[63]	train-mlogloss:0.21945	eval-mlogloss:0.14601
[64]	train-mlogloss:0.21944	eval-mlogloss:0.14607
[65]	train-mlogloss:0.22055	eval-mlogloss:0.14696
[66]	train-mlogloss:0.21998	eval-mlogloss:0.14623
[67]	train-mlogloss:0.22006	eval-mlogloss:0.14659
[68]	train-mlogloss:0.21985	eval-mlogloss:0.14586
[69]	train-mlogloss:0.21965	eval-mlogloss:0.14535
[70]	train-mlogloss:0.21963	eval-mlogloss:0.14516
[71]	train-mlogloss:0.21974	eval-mlogloss:0.14537
[72]	train-mlogloss:0.21970	eval-mlogloss:0.14505
[73]	train-mlogloss:0.21972	eval-mlogloss:0.14512
[74]	train-mlogloss:0.21970	eval-mlogloss:0.14618
[75]	train-mlogloss:0.21992	eval-mlogloss:0.14652
[76]	train-mlogloss:0.21952	eval-mlogloss:0.14593
[77]	train-mlogloss:0.21945	eval-mlogloss:0.14690
[78]	train-mlogloss:0.21991	eval-mlogloss:0.14776
[79]	train-mlogloss:0.21994	eval-mlogloss:0.14789
[80]	train-mlogloss:0.21944	eval-mlogloss:0.14756
[81]	train-mlogloss:0.21943	eval-mlogloss:0.14770
[82]	train-mlogloss:0.21926	eval-mlogloss:0.14744
[83]	train-mlogloss:0.21914	eval-mlogloss:0.14716
[84]	train-mlogloss:0.21873	eval-mlogloss:0.14677
[85]	train-mlogloss:0.21845	eval-mlogloss:0.14627
[86]	train-mlogloss:0.21845	eval-mlogloss:0.14630
[87]	train-mlogloss:0.21790	eval-mlogloss:0.14591
[88]	train-mlogloss:0.21738	eval-mlogloss:0.14539
[89]	train-mlogloss:0.21726	eval-mlogloss:0.14500
[90]	train-mlogloss:0.21735	eval-mlogloss:0.14520
[91]	train-mlogloss:0.21763	eval-mlogloss:0.14565
[92]	train-mlogloss:0.21746	eval-mlogloss:0.14540
[93]	train-mlogloss:0.21724	eval-mlogloss:0.14487
[94]	train-mlogloss:0.21736	eval-mlogloss:0.14509
[95]	train-mlogloss:0.21764	eval-mlogloss:0.14566
[96]	train-mlogloss:0.21703	eval-mlogloss:0.14529
[97]	train-mlogloss:0.21674	eval-mlogloss:0.14496
[98]	train-mlogloss:0.21749	eval-mlogloss:0.14606
[99]	train-mlogloss:0.21691	eval-mlogloss:0.14505
[100]	train-mlogloss:0.21660	eval-mlogloss:0.14436
[101]	train-mlogloss:0.21631	eval-mlogloss:0.14419
[102]	train-mlogloss:0.21637	eval-mlogloss:0.14453
[103]	train-mlogloss:0.21632	eval-mlogloss:0.14448
[104]	train-mlogloss:0.21675	eval-mlogloss:0.14505
[105]	train-mlogloss:0.21631	eval-mlogloss:0.14381
[106]	train-mlogloss:0.21646	eval-mlogloss:0.14464
[107]	train-mlogloss:0.21693	eval-mlogloss:0.14573
[108]	train-mlogloss:0.21644	eval-mlogloss:0.14475
[109]	train-mlogloss:0.21633	eval-mlogloss:0.14421
[110]	train-mlogloss:0.21641	eval-mlogloss:0.14461
[111]	train-mlogloss:0.21637	eval-mlogloss:0.14444
[112]	train-mlogloss:0.21629	eval-mlogloss:0.14411
[113]	train-mlogloss:0.21636	eval-mlogloss:0.14401
[114]	train-mlogloss:0.21626	eval-mlogloss:0.14437
[115]	train-mlogloss:0.21628	eval-mlogloss:0.14445
[116]	train-mlogloss:0.21646	eval-mlogloss:0.14506
[117]	train-mlogloss:0.21642	eval-mlogloss:0.14576
[118]	train-mlogloss:0.21623	eval-mlogloss:0.14559
[119]	train-mlogloss:0.21619	eval-mlogloss:0.14531
[120]	train-mlogloss:0.21650	eval-mlogloss:0.14543
[121]	train-mlogloss:0.21658	eval-mlogloss:0.14671
[122]	train-mlogloss:0.21650	eval-mlogloss:0.14678
[123]	train-mlogloss:0.21670	eval-mlogloss:0.14698
[124]	train-mlogloss:0.21665	eval-mlogloss:0.14640
[125]	train-mlogloss:0.21653	eval-mlogloss:0.14616
[126]	train-mlogloss:0.21650	eval-mlogloss:0.14478
[127]	train-mlogloss:0.21690	eval-mlogloss:0.14495
[128]	train-mlogloss:0.21709	eval-mlogloss:0.14558
[129]	train-mlogloss:0.21640	eval-mlogloss:0.14481
[130]	train-mlogloss:0.21689	eval-mlogloss:0.14556
[131]	train-mlogloss:0.21670	eval-mlogloss:0.14540
[132]	train-mlogloss:0.21615	eval-mlogloss:0.14442
[133]	train-mlogloss:0.21615	eval-mlogloss:0.14424
[134]	train-mlogloss:0.21616	eval-mlogloss:0.14454
[135]	train-mlogloss:0.21587	eval-mlogloss:0.14480

[I 2025-03-15 11:17:32,602] Trial 0 finished with value: 1.0 and parameters: {'lambda': 5.267681949269602e-05, 'alpha': 0.004725237220231881, 'eta': 0.2969689082106233, 'gamma': 0.0004521341175623526, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.5595932231896997, 'colsample_bytree': 0.8801714611501971}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.89068	eval-mlogloss:0.88763
[1]	train-mlogloss:0.67568	eval-mlogloss:0.65395
[2]	train-mlogloss:0.52969	eval-mlogloss:0.50029
[3]	train-mlogloss:0.42322	eval-mlogloss:0.38853
[4]	train-mlogloss:0.34833	eval-mlogloss:0.31017
[5]	train-mlogloss:0.28955	eval-mlogloss:0.24491
[6]	train-mlogloss:0.24822	eval-mlogloss:0.20205
[7]	train-mlogloss:0.21685	eval-mlogloss:0.17042
[8]	train-mlogloss:0.19376	eval-mlogloss:0.14462
[9]	train-mlogloss:0.17629	eval-mlogloss:0.12388
[10]	train-mlogloss:0.16291	eval-mlogloss:0.11253
[11]	train-mlogloss:0.15491	eval-mlogloss:0.10245
[12]	train-mlogloss:0.15041	eval-mlogloss:0.09803
[13]	train-mlogloss:0.14667	eval-mlogloss:0.09253
[14]	train-mlogloss:0.14501	eval-mlogloss:0.08979
[15]	train-mlogloss:0.14063	eval-mlogloss:0.08421
[16]	train-mlogloss:0.13762	eval-mlogloss:0.08081
[17]	train-mlogloss:0.13551	eval-mlogloss:0.07845
[18]	train-mlogloss:0.13434	eval-mlogloss:0.07858
[19]	train-mlogloss:0.13426	eval-mlogloss:0.07850
[20]	train-mlogloss:0.13337	eval-mlogloss:0.07680
[21]	train-mlogloss:0.13242	eval-mlogloss:0.07513
[22]	train-mlogloss:0.13242	eval-mlogloss:0.07513
[23]	train-mlogloss:0.13174	eval-mlogloss:0.07380
[24]	train-mlogloss:0.13174	eval-mlogloss:0.07380
[25]	train-mlogloss:0.13052	eval-mlogloss:0.07238
[26]	train-mlogloss:0.13051	eval-mlogloss:0.07237
[27]	train-mlogloss:0.13051	eval-mlogloss:0.07237
[28]	train-mlogloss:0.12980	eval-mlogloss:0.07310
[29]	train-mlogloss:0.12980	eval-mlogloss:0.07310
[30]	train-mlogloss:0.12980	eval-mlogloss:0.07310
[31]	train-mlogloss:0.12876	eval-mlogloss:0.07191
[32]	train-mlogloss:0.12876	eval-mlogloss:0.07191
[33]	train-mlogloss:0.12881	eval-mlogloss:0.07195
[34]	train-mlogloss:0.12881	eval-mlogloss:0.07195
[35]	train-mlogloss:0.12821	eval-mlogloss:0.07059
[36]	train-mlogloss:0.12626	eval-mlogloss:0.06837
[37]	train-mlogloss:0.12628	eval-mlogloss:0.06838
[38]	train-mlogloss:0.12628	eval-mlogloss:0.06838
[39]	train-mlogloss:0.12628	eval-mlogloss:0.06838
[40]	train-mlogloss:0.12628	eval-mlogloss:0.06838
[41]	train-mlogloss:0.12545	eval-mlogloss:0.06873
[42]	train-mlogloss:0.12545	eval-mlogloss:0.06873
[43]	train-mlogloss:0.12545	eval-mlogloss:0.06873
[44]	train-mlogloss:0.12545	eval-mlogloss:0.06873
[45]	train-mlogloss:0.12545	eval-mlogloss:0.06873
[46]	train-mlogloss:0.12545	eval-mlogloss:0.06875
[47]	train-mlogloss:0.12545	eval-mlogloss:0.06875
[48]	train-mlogloss:0.12545	eval-mlogloss:0.06875
[49]	train-mlogloss:0.12465	eval-mlogloss:0.06763
[50]	train-mlogloss:0.12465	eval-mlogloss:0.06763
[51]	train-mlogloss:0.12466	eval-mlogloss:0.06763
[52]	train-mlogloss:0.12464	eval-mlogloss:0.06763
[53]	train-mlogloss:0.12467	eval-mlogloss:0.06761
[54]	train-mlogloss:0.12467	eval-mlogloss:0.06761
[55]	train-mlogloss:0.12467	eval-mlogloss:0.06761
[56]	train-mlogloss:0.12467	eval-mlogloss:0.06761
[57]	train-mlogloss:0.12460	eval-mlogloss:0.06750
[58]	train-mlogloss:0.12465	eval-mlogloss:0.06749
[59]	train-mlogloss:0.12406	eval-mlogloss:0.06708
[60]	train-mlogloss:0.12403	eval-mlogloss:0.06709
[61]	train-mlogloss:0.12403	eval-mlogloss:0.06709
[62]	train-mlogloss:0.12403	eval-mlogloss:0.06709
[63]	train-mlogloss:0.12404	eval-mlogloss:0.06709
[64]	train-mlogloss:0.12404	eval-mlogloss:0.06709
[65]	train-mlogloss:0.12312	eval-mlogloss:0.06575
[66]	train-mlogloss:0.12316	eval-mlogloss:0.06572
[67]	train-mlogloss:0.12316	eval-mlogloss:0.06572
[68]	train-mlogloss:0.12315	eval-mlogloss:0.06572
[69]	train-mlogloss:0.12317	eval-mlogloss:0.06573
[70]	train-mlogloss:0.12317	eval-mlogloss:0.06573
[71]	train-mlogloss:0.12317	eval-mlogloss:0.06573
[72]	train-mlogloss:0.12321	eval-mlogloss:0.06573
[73]	train-mlogloss:0.12321	eval-mlogloss:0.06573
[74]	train-mlogloss:0.12321	eval-mlogloss:0.06573
[75]	train-mlogloss:0.12321	eval-mlogloss:0.06573
[76]	train-mlogloss:0.12326	eval-mlogloss:0.06573
[77]	train-mlogloss:0.12325	eval-mlogloss:0.06573
[78]	train-mlogloss:0.12264	eval-mlogloss:0.06550
[79]	train-mlogloss:0.12264	eval-mlogloss:0.06550
[80]	train-mlogloss:0.12264	eval-mlogloss:0.06550
[81]	train-mlogloss:0.12247	eval-mlogloss:0.06548
[82]	train-mlogloss:0.12141	eval-mlogloss:0.06667
[83]	train-mlogloss:0.12141	eval-mlogloss:0.06668
[84]	train-mlogloss:0.12141	eval-mlogloss:0.06668
[85]	train-mlogloss:0.12137	eval-mlogloss:0.06667
[86]	train-mlogloss:0.12137	eval-mlogloss:0.06667
[87]	train-mlogloss:0.12137	eval-mlogloss:0.06667
[88]	train-mlogloss:0.12137	eval-mlogloss:0.06667
[89]	train-mlogloss:0.12073	eval-mlogloss:0.06590
[90]	train-mlogloss:0.12072	eval-mlogloss:0.06591
[91]	train-mlogloss:0.12071	eval-mlogloss:0.06592
[92]	train-mlogloss:0.12071	eval-mlogloss:0.06592
[93]	train-mlogloss:0.12072	eval-mlogloss:0.06591
[94]	train-mlogloss:0.12071	eval-mlogloss:0.06592
[95]	train-mlogloss:0.12092	eval-mlogloss:0.06601
[96]	train-mlogloss:0.12094	eval-mlogloss:0.06599
[97]	train-mlogloss:0.12094	eval-mlogloss:0.06599
[98]	train-mlogloss:0.12048	eval-mlogloss:0.06581
[99]	train-mlogloss:0.12048	eval-mlogloss:0.06581
[100]	train-mlogloss:0.12047	eval-mlogloss:0.06577
[101]	train-mlogloss:0.11945	eval-mlogloss:0.06417
[102]	train-mlogloss:0.11945	eval-mlogloss:0.06417
[103]	train-mlogloss:0.11945	eval-mlogloss:0.06417
[104]	train-mlogloss:0.11943	eval-mlogloss:0.06420
[105]	train-mlogloss:0.11932	eval-mlogloss:0.06416
[106]	train-mlogloss:0.11932	eval-mlogloss:0.06416
[107]	train-mlogloss:0.11930	eval-mlogloss:0.06421
[108]	train-mlogloss:0.11930	eval-mlogloss:0.06419
[109]	train-mlogloss:0.11930	eval-mlogloss:0.06419
[110]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[111]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[112]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[113]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[114]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[115]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[116]	train-mlogloss:0.11932	eval-mlogloss:0.06423
[117]	train-mlogloss:0.11934	eval-mlogloss:0.06418
[118]	train-mlogloss:0.11931	eval-mlogloss:0.06418
[119]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[120]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[121]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[122]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[123]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[124]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[125]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[126]	train-mlogloss:0.11896	eval-mlogloss:0.06364
[127]	train-mlogloss:0.11900	eval-mlogloss:0.06364
[128]	train-mlogloss:0.11900	eval-mlogloss:0.06365
[129]	train-mlogloss:0.11899	eval-mlogloss:0.06365
[130]	train-mlogloss:0.11902	eval-mlogloss:0.06366
[131]	train-mlogloss:0.11901	eval-mlogloss:0.06368
[132]	train-mlogloss:0.11841	eval-mlogloss:0.06261
[133]	train-mlogloss:0.11841	eval-mlogloss:0.06261
[134]	train-mlogloss:0.11835	eval-mlogloss:0.06262
[135]	train-mlogloss:0.11833	eval-mlogloss:0.06264
[136]	train-mlogloss:0.11833	eval-mlogloss:0.06264
[137]	train-mlogloss:0.11833	eval-mlogloss:0.06264
[138]	train-mlogloss:0.11834	eval-mlogloss:0.06263
[139]	train-mlogloss:0.11834	eval-mlogloss:0.06263
[140]	train-mlogloss:0.11834	eval-mlogloss:0.06263
[141]	train-mlogloss:0.11835	eval-mlogloss:0.06265
[142]	train-mlogloss:0.11835	eval-mlogloss:0.06267
[143]	train-mlogloss:0.11835	eval-mlogloss:0.06267
[144]	train-mlogloss:0.11835	eval-mlogloss:0.06267
[145]	train-mlogloss:0.11836	eval-mlogloss:0.06267
[146]	train-mlogloss:0.11836	eval-mlogloss:0.06266
[147]	train-mlogloss:0.11835	eval-mlogloss:0.06266
[148]	train-mlogloss:0.11835	eval-mlogloss:0.06266
[149]	train-mlogloss:0.11788	eval-mlogloss:0.06254
[150]	train-mlogloss:0.11788	eval-mlogloss:0.06251
[151]	train-mlogloss:0.11788	eval-mlogloss:0.06251
[152]	train-mlogloss:0.11799	eval-mlogloss:0.06256
[153]	train-mlogloss:0.11799	eval-mlogloss:0.06256
[154]	train-mlogloss:0.11794	eval-mlogloss:0.06246
[155]	train-mlogloss:0.11794	eval-mlogloss:0.06242
[156]	train-mlogloss:0.11796	eval-mlogloss:0.06238
[157]	train-mlogloss:0.11793	eval-mlogloss:0.06238
[158]	train-mlogloss:0.11786	eval-mlogloss:0.06239
[159]	train-mlogloss:0.11743	eval-mlogloss:0.06216
[160]	train-mlogloss:0.11694	eval-mlogloss:0.06187
[161]	train-mlogloss:0.11697	eval-mlogloss:0.06188
[162]	train-mlogloss:0.11697	eval-mlogloss:0.06188
[163]	train-mlogloss:0.11697	eval-mlogloss:0.06188
[164]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[165]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[166]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[167]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[168]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[169]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[170]	train-mlogloss:0.11702	eval-mlogloss:0.06190
[171]	train-mlogloss:0.11696	eval-mlogloss:0.06187
[172]	train-mlogloss:0.11696	eval-mlogloss:0.06187
[173]	train-mlogloss:0.11696	eval-mlogloss:0.06187
[174]	train-mlogloss:0.11696	eval-mlogloss:0.06187
[175]	train-mlogloss:0.11696	eval-mlogloss:0.06187
[176]	train-mlogloss:0.11696	eval-mlogloss:0.06184
[177]	train-mlogloss:0.11696	eval-mlogloss:0.06184
[178]	train-mlogloss:0.11623	eval-mlogloss:0.06246
[179]	train-mlogloss:0.11623	eval-mlogloss:0.06246
[180]	train-mlogloss:0.11627	eval-mlogloss:0.06247
[181]	train-mlogloss:0.11627	eval-mlogloss:0.06247
[182]	train-mlogloss:0.11632	eval-mlogloss:0.06242
[183]	train-mlogloss:0.11624	eval-mlogloss:0.06246
[184]	train-mlogloss:0.11624	eval-mlogloss:0.06246
[185]	train-mlogloss:0.11624	eval-mlogloss:0.06246
[186]	train-mlogloss:0.11624	eval-mlogloss:0.06246
[187]	train-mlogloss:0.11623	eval-mlogloss:0.06247
[188]	train-mlogloss:0.11623	eval-mlogloss:0.06247
[189]	train-mlogloss:0.11622	eval-mlogloss:0.06246
[190]	train-mlogloss:0.11622	eval-mlogloss:0.06246
[191]	train-mlogloss:0.11621	eval-mlogloss:0.06247
[192]	train-mlogloss:0.11621	eval-mlogloss:0.06247
[193]	train-mlogloss:0.11621	eval-mlogloss:0.06248
[194]	train-mlogloss:0.11573	eval-mlogloss:0.06134
[195]	train-mlogloss:0.11573	eval-mlogloss:0.06134
[196]	train-mlogloss:0.11570	eval-mlogloss:0.06135
[197]	train-mlogloss:0.11577	eval-mlogloss:0.06134
[198]	train-mlogloss:0.11581	eval-mlogloss:0.06134
[199]	train-mlogloss:0.11581	eval-mlogloss:0.06134
[200]	train-mlogloss:0.11581	eval-mlogloss:0.06134
[201]	train-mlogloss:0.11588	eval-mlogloss:0.06135
[202]	train-mlogloss:0.11586	eval-mlogloss:0.06134
[203]	train-mlogloss:0.11575	eval-mlogloss:0.06134
[204]	train-mlogloss:0.11575	eval-mlogloss:0.06134
[205]	train-mlogloss:0.11575	eval-mlogloss:0.06134
[206]	train-mlogloss:0.11574	eval-mlogloss:0.06134
[207]	train-mlogloss:0.11575	eval-mlogloss:0.06136
[208]	train-mlogloss:0.11572	eval-mlogloss:0.06136
[209]	train-mlogloss:0.11521	eval-mlogloss:0.06201
[210]	train-mlogloss:0.11521	eval-mlogloss:0.06201
[211]	train-mlogloss:0.11521	eval-mlogloss:0.06201
[212]	train-mlogloss:0.11520	eval-mlogloss:0.06199
[213]	train-mlogloss:0.11520	eval-mlogloss:0.06199
[214]	train-mlogloss:0.11520	eval-mlogloss:0.06199
[215]	train-mlogloss:0.11515	eval-mlogloss:0.06199
[216]	train-mlogloss:0.11512	eval-mlogloss:0.06200
[217]	train-mlogloss:0.11511	eval-mlogloss:0.06200
[218]	train-mlogloss:0.11478	eval-mlogloss:0.06252
[219]	train-mlogloss:0.11478	eval-mlogloss:0.06252
[220]	train-mlogloss:0.11478	eval-mlogloss:0.06252
[221]	train-mlogloss:0.11475	eval-mlogloss:0.06253
[222]	train-mlogloss:0.11474	eval-mlogloss:0.06251
[223]	train-mlogloss:0.11475	eval-mlogloss:0.06256
[224]	train-mlogloss:0.11473	eval-mlogloss:0.06257
[225]	train-mlogloss:0.11473	eval-mlogloss:0.06257
[226]	train-mlogloss:0.11473	eval-mlogloss:0.06257
[227]	train-mlogloss:0.11471	eval-mlogloss:0.06258

[I 2025-03-15 11:17:35,921] Trial 1 finished with value: 1.0 and parameters: {'lambda': 5.080575461867694e-05, 'alpha': 0.7736081425883948, 'eta': 0.26179839684800554, 'gamma': 0.15950197665711158, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7671647147419236, 'colsample_bytree': 0.5066434038328064}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00250	eval-mlogloss:1.00376
[1]	train-mlogloss:0.79199	eval-mlogloss:0.78064
[2]	train-mlogloss:0.64164	eval-mlogloss:0.61892
[3]	train-mlogloss:0.55613	eval-mlogloss:0.52344
[4]	train-mlogloss:0.47963	eval-mlogloss:0.44241
[5]	train-mlogloss:0.40058	eval-mlogloss:0.35776
[6]	train-mlogloss:0.35525	eval-mlogloss:0.31483
[7]	train-mlogloss:0.32499	eval-mlogloss:0.28414
[8]	train-mlogloss:0.28427	eval-mlogloss:0.23692
[9]	train-mlogloss:0.25871	eval-mlogloss:0.21029
[10]	train-mlogloss:0.23107	eval-mlogloss:0.17942
[11]	train-mlogloss:0.21341	eval-mlogloss:0.15868
[12]	train-mlogloss:0.21003	eval-mlogloss:0.15588
[13]	train-mlogloss:0.19288	eval-mlogloss:0.13481
[14]	train-mlogloss:0.19161	eval-mlogloss:0.13605
[15]	train-mlogloss:0.18748	eval-mlogloss:0.13196
[16]	train-mlogloss:0.18175	eval-mlogloss:0.12532
[17]	train-mlogloss:0.17678	eval-mlogloss:0.11954
[18]	train-mlogloss:0.17446	eval-mlogloss:0.11903
[19]	train-mlogloss:0.17346	eval-mlogloss:0.11979
[20]	train-mlogloss:0.16942	eval-mlogloss:0.11404
[21]	train-mlogloss:0.16913	eval-mlogloss:0.11359
[22]	train-mlogloss:0.16685	eval-mlogloss:0.11069
[23]	train-mlogloss:0.15961	eval-mlogloss:0.10172
[24]	train-mlogloss:0.15877	eval-mlogloss:0.10069
[25]	train-mlogloss:0.15550	eval-mlogloss:0.09689
[26]	train-mlogloss:0.15547	eval-mlogloss:0.09684
[27]	train-mlogloss:0.15474	eval-mlogloss:0.09645
[28]	train-mlogloss:0.15469	eval-mlogloss:0.09659
[29]	train-mlogloss:0.15466	eval-mlogloss:0.09672
[30]	train-mlogloss:0.15344	eval-mlogloss:0.09462
[31]	train-mlogloss:0.15349	eval-mlogloss:0.09459
[32]	train-mlogloss:0.15353	eval-mlogloss:0.09475
[33]	train-mlogloss:0.15352	eval-mlogloss:0.09453
[34]	train-mlogloss:0.15346	eval-mlogloss:0.09466
[35]	train-mlogloss:0.15289	eval-mlogloss:0.09404
[36]	train-mlogloss:0.15237	eval-mlogloss:0.09382
[37]	train-mlogloss:0.15175	eval-mlogloss:0.09437
[38]	train-mlogloss:0.15177	eval-mlogloss:0.09433
[39]	train-mlogloss:0.15174	eval-mlogloss:0.09439
[40]	train-mlogloss:0.15174	eval-mlogloss:0.09443
[41]	train-mlogloss:0.15175	eval-mlogloss:0.09439
[42]	train-mlogloss:0.15177	eval-mlogloss:0.09440
[43]	train-mlogloss:0.15129	eval-mlogloss:0.09375
[44]	train-mlogloss:0.15125	eval-mlogloss:0.09382
[45]	train-mlogloss:0.15058	eval-mlogloss:0.09362
[46]	train-mlogloss:0.15064	eval-mlogloss:0.09350
[47]	train-mlogloss:0.15063	eval-mlogloss:0.09342
[48]	train-mlogloss:0.15062	eval-mlogloss:0.09347
[49]	train-mlogloss:0.15063	eval-mlogloss:0.09341
[50]	train-mlogloss:0.15066	eval-mlogloss:0.09336
[51]	train-mlogloss:0.15066	eval-mlogloss:0.09334
[52]	train-mlogloss:0.15068	eval-mlogloss:0.09340
[53]	train-mlogloss:0.15076	eval-mlogloss:0.09345
[54]	train-mlogloss:0.15066	eval-mlogloss:0.09341
[55]	train-mlogloss:0.14869	eval-mlogloss:0.09085
[56]	train-mlogloss:0.14868	eval-mlogloss:0.09094
[57]	train-mlogloss:0.14845	eval-mlogloss:0.09028
[58]	train-mlogloss:0.14849	eval-mlogloss:0.09019
[59]	train-mlogloss:0.14788	eval-mlogloss:0.08998
[60]	train-mlogloss:0.14779	eval-mlogloss:0.09025
[61]	train-mlogloss:0.14783	eval-mlogloss:0.09036
[62]	train-mlogloss:0.14781	eval-mlogloss:0.09035
[63]	train-mlogloss:0.14783	eval-mlogloss:0.09019
[64]	train-mlogloss:0.14781	eval-mlogloss:0.09018
[65]	train-mlogloss:0.14792	eval-mlogloss:0.09044
[66]	train-mlogloss:0.14742	eval-mlogloss:0.08952
[67]	train-mlogloss:0.14744	eval-mlogloss:0.08964
[68]	train-mlogloss:0.14671	eval-mlogloss:0.08901
[69]	train-mlogloss:0.14629	eval-mlogloss:0.08778
[70]	train-mlogloss:0.14629	eval-mlogloss:0.08769
[71]	train-mlogloss:0.14617	eval-mlogloss:0.08760
[72]	train-mlogloss:0.14619	eval-mlogloss:0.08741
[73]	train-mlogloss:0.14622	eval-mlogloss:0.08731
[74]	train-mlogloss:0.14619	eval-mlogloss:0.08736
[75]	train-mlogloss:0.14617	eval-mlogloss:0.08750
[76]	train-mlogloss:0.14619	eval-mlogloss:0.08739
[77]	train-mlogloss:0.14617	eval-mlogloss:0.08749
[78]	train-mlogloss:0.14637	eval-mlogloss:0.08766
[79]	train-mlogloss:0.14632	eval-mlogloss:0.08761
[80]	train-mlogloss:0.14633	eval-mlogloss:0.08761
[81]	train-mlogloss:0.14632	eval-mlogloss:0.08786
[82]	train-mlogloss:0.14634	eval-mlogloss:0.08793
[83]	train-mlogloss:0.14656	eval-mlogloss:0.08861
[84]	train-mlogloss:0.14553	eval-mlogloss:0.08954
[85]	train-mlogloss:0.14533	eval-mlogloss:0.08940
[86]	train-mlogloss:0.14540	eval-mlogloss:0.08947
[87]	train-mlogloss:0.14541	eval-mlogloss:0.08932
[88]	train-mlogloss:0.14538	eval-mlogloss:0.08926
[89]	train-mlogloss:0.14468	eval-mlogloss:0.08795
[90]	train-mlogloss:0.14472	eval-mlogloss:0.08795
[91]	train-mlogloss:0.14473	eval-mlogloss:0.08797
[92]	train-mlogloss:0.14467	eval-mlogloss:0.08806
[93]	train-mlogloss:0.14464	eval-mlogloss:0.08795
[94]	train-mlogloss:0.14469	eval-mlogloss:0.08796
[95]	train-mlogloss:0.14483	eval-mlogloss:0.08796
[96]	train-mlogloss:0.14487	eval-mlogloss:0.08792
[97]	train-mlogloss:0.14486	eval-mlogloss:0.08795
[98]	train-mlogloss:0.14439	eval-mlogloss:0.08778
[99]	train-mlogloss:0.14424	eval-mlogloss:0.08758
[100]	train-mlogloss:0.14413	eval-mlogloss:0.08740
[101]	train-mlogloss:0.14403	eval-mlogloss:0.08744
[102]	train-mlogloss:0.14400	eval-mlogloss:0.08746

[I 2025-03-15 11:17:37,621] Trial 2 finished with value: 1.0 and parameters: {'lambda': 1.837113713653658e-06, 'alpha': 0.001181695114796977, 'eta': 0.2010156403697263, 'gamma': 0.33968704433646413, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.6852946245303172, 'colsample_bytree': 0.4605947552362611}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04612	eval-mlogloss:1.04289
[1]	train-mlogloss:1.00256	eval-mlogloss:1.00009
[2]	train-mlogloss:0.95608	eval-mlogloss:0.95174
[3]	train-mlogloss:0.91085	eval-mlogloss:0.90487
[4]	train-mlogloss:0.87034	eval-mlogloss:0.86242
[5]	train-mlogloss:0.83067	eval-mlogloss:0.82074
[6]	train-mlogloss:0.79389	eval-mlogloss:0.78233
[7]	train-mlogloss:0.76156	eval-mlogloss:0.74765
[8]	train-mlogloss:0.73046	eval-mlogloss:0.71427
[9]	train-mlogloss:0.70086	eval-mlogloss:0.68217
[10]	train-mlogloss:0.67316	eval-mlogloss:0.65185
[11]	train-mlogloss:0.64616	eval-mlogloss:0.62216
[12]	train-mlogloss:0.62135	eval-mlogloss:0.59607
[13]	train-mlogloss:0.59759	eval-mlogloss:0.57081
[14]	train-mlogloss:0.57423	eval-mlogloss:0.54604
[15]	train-mlogloss:0.55234	eval-mlogloss:0.52246
[16]	train-mlogloss:0.53166	eval-mlogloss:0.50032
[17]	train-mlogloss:0.51238	eval-mlogloss:0.47954
[18]	train-mlogloss:0.49358	eval-mlogloss:0.46026
[19]	train-mlogloss:0.47567	eval-mlogloss:0.44199
[20]	train-mlogloss:0.45841	eval-mlogloss:0.42307
[21]	train-mlogloss:0.44291	eval-mlogloss:0.40606
[22]	train-mlogloss:0.42732	eval-mlogloss:0.38858
[23]	train-mlogloss:0.41197	eval-mlogloss:0.37248
[24]	train-mlogloss:0.39791	eval-mlogloss:0.35712
[25]	train-mlogloss:0.38590	eval-mlogloss:0.34332
[26]	train-mlogloss:0.37318	eval-mlogloss:0.32956
[27]	train-mlogloss:0.36194	eval-mlogloss:0.31797
[28]	train-mlogloss:0.35175	eval-mlogloss:0.30650
[29]	train-mlogloss:0.34098	eval-mlogloss:0.29440
[30]	train-mlogloss:0.33113	eval-mlogloss:0.28399
[31]	train-mlogloss:0.32248	eval-mlogloss:0.27524
[32]	train-mlogloss:0.31365	eval-mlogloss:0.26555
[33]	train-mlogloss:0.30583	eval-mlogloss:0.25569
[34]	train-mlogloss:0.29658	eval-mlogloss:0.24617
[35]	train-mlogloss:0.28975	eval-mlogloss:0.23832
[36]	train-mlogloss:0.28285	eval-mlogloss:0.23145
[37]	train-mlogloss:0.27608	eval-mlogloss:0.22405
[38]	train-mlogloss:0.27036	eval-mlogloss:0.21910
[39]	train-mlogloss:0.26342	eval-mlogloss:0.21148
[40]	train-mlogloss:0.25669	eval-mlogloss:0.20404
[41]	train-mlogloss:0.25107	eval-mlogloss:0.19743
[42]	train-mlogloss:0.24534	eval-mlogloss:0.19099
[43]	train-mlogloss:0.24015	eval-mlogloss:0.18455
[44]	train-mlogloss:0.23495	eval-mlogloss:0.17817
[45]	train-mlogloss:0.22960	eval-mlogloss:0.17161
[46]	train-mlogloss:0.22519	eval-mlogloss:0.16668
[47]	train-mlogloss:0.22143	eval-mlogloss:0.16258
[48]	train-mlogloss:0.21742	eval-mlogloss:0.15795
[49]	train-mlogloss:0.21313	eval-mlogloss:0.15343
[50]	train-mlogloss:0.21156	eval-mlogloss:0.15130
[51]	train-mlogloss:0.20778	eval-mlogloss:0.14714
[52]	train-mlogloss:0.20504	eval-mlogloss:0.14379
[53]	train-mlogloss:0.20432	eval-mlogloss:0.14276
[54]	train-mlogloss:0.20130	eval-mlogloss:0.13954
[55]	train-mlogloss:0.19849	eval-mlogloss:0.13655
[56]	train-mlogloss:0.19676	eval-mlogloss:0.13447
[57]	train-mlogloss:0.19584	eval-mlogloss:0.13311
[58]	train-mlogloss:0.19454	eval-mlogloss:0.13131
[59]	train-mlogloss:0.19432	eval-mlogloss:0.13103
[60]	train-mlogloss:0.19395	eval-mlogloss:0.13116
[61]	train-mlogloss:0.19374	eval-mlogloss:0.13101
[62]	train-mlogloss:0.19124	eval-mlogloss:0.12854
[63]	train-mlogloss:0.19118	eval-mlogloss:0.12837
[64]	train-mlogloss:0.19056	eval-mlogloss:0.12748
[65]	train-mlogloss:0.19040	eval-mlogloss:0.12739
[66]	train-mlogloss:0.19022	eval-mlogloss:0.12710
[67]	train-mlogloss:0.18923	eval-mlogloss:0.12575
[68]	train-mlogloss:0.18888	eval-mlogloss:0.12526
[69]	train-mlogloss:0.18783	eval-mlogloss:0.12387
[70]	train-mlogloss:0.18720	eval-mlogloss:0.12297
[71]	train-mlogloss:0.18714	eval-mlogloss:0.12290
[72]	train-mlogloss:0.18609	eval-mlogloss:0.12134
[73]	train-mlogloss:0.18525	eval-mlogloss:0.12012
[74]	train-mlogloss:0.18522	eval-mlogloss:0.12003
[75]	train-mlogloss:0.18477	eval-mlogloss:0.11947
[76]	train-mlogloss:0.18467	eval-mlogloss:0.11929
[77]	train-mlogloss:0.18447	eval-mlogloss:0.11904
[78]	train-mlogloss:0.18431	eval-mlogloss:0.11893
[79]	train-mlogloss:0.18373	eval-mlogloss:0.11810
[80]	train-mlogloss:0.18373	eval-mlogloss:0.11812
[81]	train-mlogloss:0.18287	eval-mlogloss:0.11687
[82]	train-mlogloss:0.18195	eval-mlogloss:0.11586
[83]	train-mlogloss:0.18158	eval-mlogloss:0.11539
[84]	train-mlogloss:0.18077	eval-mlogloss:0.11455
[85]	train-mlogloss:0.18051	eval-mlogloss:0.11442
[86]	train-mlogloss:0.18037	eval-mlogloss:0.11437
[87]	train-mlogloss:0.18032	eval-mlogloss:0.11431
[88]	train-mlogloss:0.18011	eval-mlogloss:0.11414
[89]	train-mlogloss:0.17973	eval-mlogloss:0.11358
[90]	train-mlogloss:0.17915	eval-mlogloss:0.11284
[91]	train-mlogloss:0.17917	eval-mlogloss:0.11286
[92]	train-mlogloss:0.17916	eval-mlogloss:0.11285
[93]	train-mlogloss:0.17914	eval-mlogloss:0.11281
[94]	train-mlogloss:0.17916	eval-mlogloss:0.11283
[95]	train-mlogloss:0.17902	eval-mlogloss:0.11273
[96]	train-mlogloss:0.17903	eval-mlogloss:0.11275
[97]	train-mlogloss:0.17836	eval-mlogloss:0.11204
[98]	train-mlogloss:0.17817	eval-mlogloss:0.11200
[99]	train-mlogloss:0.17756	eval-mlogloss:0.11131
[100]	train-mlogloss:0.17754	eval-mlogloss:0.11127
[101]	train-mlogloss:0.17670	eval-mlogloss:0.11047
[102]	train-mlogloss:0.17659	eval-mlogloss:0.11037
[103]	train-mlogloss:0.17602	eval-mlogloss:0.10959
[104]	train-mlogloss:0.17604	eval-mlogloss:0.10964
[105]	train-mlogloss:0.17566	eval-mlogloss:0.10910
[106]	train-mlogloss:0.17568	eval-mlogloss:0.10915
[107]	train-mlogloss:0.17561	eval-mlogloss:0.10872
[108]	train-mlogloss:0.17558	eval-mlogloss:0.10869
[109]	train-mlogloss:0.17543	eval-mlogloss:0.10845
[110]	train-mlogloss:0.17522	eval-mlogloss:0.10818
[111]	train-mlogloss:0.17524	eval-mlogloss:0.10820
[112]	train-mlogloss:0.17452	eval-mlogloss:0.10740
[113]	train-mlogloss:0.17440	eval-mlogloss:0.10674
[114]	train-mlogloss:0.17430	eval-mlogloss:0.10656
[115]	train-mlogloss:0.17431	eval-mlogloss:0.10656
[116]	train-mlogloss:0.17417	eval-mlogloss:0.10649
[117]	train-mlogloss:0.17412	eval-mlogloss:0.10630
[118]	train-mlogloss:0.17408	eval-mlogloss:0.10629
[119]	train-mlogloss:0.17405	eval-mlogloss:0.10624
[120]	train-mlogloss:0.17395	eval-mlogloss:0.10605
[121]	train-mlogloss:0.17396	eval-mlogloss:0.10609
[122]	train-mlogloss:0.17376	eval-mlogloss:0.10600
[123]	train-mlogloss:0.17332	eval-mlogloss:0.10536
[124]	train-mlogloss:0.17271	eval-mlogloss:0.10468
[125]	train-mlogloss:0.17269	eval-mlogloss:0.10466
[126]	train-mlogloss:0.17208	eval-mlogloss:0.10383
[127]	train-mlogloss:0.17199	eval-mlogloss:0.10377
[128]	train-mlogloss:0.17199	eval-mlogloss:0.10376
[129]	train-mlogloss:0.17146	eval-mlogloss:0.10327
[130]	train-mlogloss:0.17136	eval-mlogloss:0.10322
[131]	train-mlogloss:0.17135	eval-mlogloss:0.10323
[132]	train-mlogloss:0.17056	eval-mlogloss:0.10233
[133]	train-mlogloss:0.17054	eval-mlogloss:0.10231
[134]	train-mlogloss:0.17055	eval-mlogloss:0.10235
[135]	train-mlogloss:0.16958	eval-mlogloss:0.10112
[136]	train-mlogloss:0.16959	eval-mlogloss:0.10113
[137]	train-mlogloss:0.16959	eval-mlogloss:0.10112
[138]	train-mlogloss:0.16953	eval-mlogloss:0.10103
[139]	train-mlogloss:0.16937	eval-mlogloss:0.10096
[140]	train-mlogloss:0.16932	eval-mlogloss:0.10091
[141]	train-mlogloss:0.16927	eval-mlogloss:0.10055
[142]	train-mlogloss:0.16922	eval-mlogloss:0.10059
[143]	train-mlogloss:0.16913	eval-mlogloss:0.10059
[144]	train-mlogloss:0.16908	eval-mlogloss:0.10055
[145]	train-mlogloss:0.16911	eval-mlogloss:0.10060
[146]	train-mlogloss:0.16893	eval-mlogloss:0.10028
[147]	train-mlogloss:0.16856	eval-mlogloss:0.09973
[148]	train-mlogloss:0.16855	eval-mlogloss:0.09974
[149]	train-mlogloss:0.16856	eval-mlogloss:0.09976
[150]	train-mlogloss:0.16849	eval-mlogloss:0.09980
[151]	train-mlogloss:0.16849	eval-mlogloss:0.09979
[152]	train-mlogloss:0.16852	eval-mlogloss:0.09982
[153]	train-mlogloss:0.16851	eval-mlogloss:0.09980
[154]	train-mlogloss:0.16845	eval-mlogloss:0.09962
[155]	train-mlogloss:0.16841	eval-mlogloss:0.09952
[156]	train-mlogloss:0.16821	eval-mlogloss:0.09962
[157]	train-mlogloss:0.16819	eval-mlogloss:0.09960
[158]	train-mlogloss:0.16817	eval-mlogloss:0.09961
[159]	train-mlogloss:0.16803	eval-mlogloss:0.09954
[160]	train-mlogloss:0.16790	eval-mlogloss:0.09948
[161]	train-mlogloss:0.16790	eval-mlogloss:0.09947
[162]	train-mlogloss:0.16773	eval-mlogloss:0.09940
[163]	train-mlogloss:0.16772	eval-mlogloss:0.09942
[164]	train-mlogloss:0.16765	eval-mlogloss:0.09938
[165]	train-mlogloss:0.16721	eval-mlogloss:0.09868
[166]	train-mlogloss:0.16717	eval-mlogloss:0.09873
[167]	train-mlogloss:0.16718	eval-mlogloss:0.09875
[168]	train-mlogloss:0.16718	eval-mlogloss:0.09877
[169]	train-mlogloss:0.16703	eval-mlogloss:0.09868
[170]	train-mlogloss:0.16703	eval-mlogloss:0.09869
[171]	train-mlogloss:0.16704	eval-mlogloss:0.09873
[172]	train-mlogloss:0.16703	eval-mlogloss:0.09869
[173]	train-mlogloss:0.16704	eval-mlogloss:0.09871
[174]	train-mlogloss:0.16707	eval-mlogloss:0.09880
[175]	train-mlogloss:0.16708	eval-mlogloss:0.09879
[176]	train-mlogloss:0.16681	eval-mlogloss:0.09834
[177]	train-mlogloss:0.16652	eval-mlogloss:0.09791
[178]	train-mlogloss:0.16649	eval-mlogloss:0.09790
[179]	train-mlogloss:0.16650	eval-mlogloss:0.09789
[180]	train-mlogloss:0.16646	eval-mlogloss:0.09747
[181]	train-mlogloss:0.16644	eval-mlogloss:0.09744
[182]	train-mlogloss:0.16642	eval-mlogloss:0.09737
[183]	train-mlogloss:0.16643	eval-mlogloss:0.09743
[184]	train-mlogloss:0.16633	eval-mlogloss:0.09729
[185]	train-mlogloss:0.16634	eval-mlogloss:0.09730
[186]	train-mlogloss:0.16632	eval-mlogloss:0.09716
[187]	train-mlogloss:0.16632	eval-mlogloss:0.09713
[188]	train-mlogloss:0.16619	eval-mlogloss:0.09710
[189]	train-mlogloss:0.16619	eval-mlogloss:0.09713
[190]	train-mlogloss:0.16622	eval-mlogloss:0.09722
[191]	train-mlogloss:0.16621	eval-mlogloss:0.09719
[192]	train-mlogloss:0.16619	eval-mlogloss:0.09720
[193]	train-mlogloss:0.16617	eval-mlogloss:0.09718
[194]	train-mlogloss:0.16599	eval-mlogloss:0.09706
[195]	train-mlogloss:0.16599	eval-mlogloss:0.09703
[196]	train-mlogloss:0.16599	eval-mlogloss:0.09702
[197]	train-mlogloss:0.16596	eval-mlogloss:0.09699
[198]	train-mlogloss:0.16596	eval-mlogloss:0.09694
[199]	train-mlogloss:0.16594	eval-mlogloss:0.09690
[200]	train-mlogloss:0.16594	eval-mlogloss:0.09688
[201]	train-mlogloss:0.16594	eval-mlogloss:0.09684
[202]	train-mlogloss:0.16580	eval-mlogloss:0.09673
[203]	train-mlogloss:0.16579	eval-mlogloss:0.09674
[204]	train-mlogloss:0.16568	eval-mlogloss:0.09669
[205]	train-mlogloss:0.16568	eval-mlogloss:0.09667
[206]	train-mlogloss:0.16566	eval-mlogloss:0.09669
[207]	train-mlogloss:0.16566	eval-mlogloss:0.09668
[208]	train-mlogloss:0.16565	eval-mlogloss:0.09670
[209]	train-mlogloss:0.16554	eval-mlogloss:0.09650
[210]	train-mlogloss:0.16549	eval-mlogloss:0.09612
[211]	train-mlogloss:0.16537	eval-mlogloss:0.09603
[212]	train-mlogloss:0.16533	eval-mlogloss:0.09568
[213]	train-mlogloss:0.16532	eval-mlogloss:0.09570
[214]	train-mlogloss:0.16533	eval-mlogloss:0.09568
[215]	train-mlogloss:0.16519	eval-mlogloss:0.09566
[216]	train-mlogloss:0.16472	eval-mlogloss:0.09498
[217]	train-mlogloss:0.16472	eval-mlogloss:0.09498
[218]	train-mlogloss:0.16431	eval-mlogloss:0.09435
[219]	train-mlogloss:0.16431	eval-mlogloss:0.09434
[220]	train-mlogloss:0.16420	eval-mlogloss:0.09432
[221]	train-mlogloss:0.16398	eval-mlogloss:0.09407
[222]	train-mlogloss:0.16397	eval-mlogloss:0.09405
[223]	train-mlogloss:0.16396	eval-mlogloss:0.09406
[224]	train-mlogloss:0.16395	eval-mlogloss:0.09407
[225]	train-mlogloss:0.16394	eval-mlogloss:0.09408
[226]	train-mlogloss:0.16395	eval-mlogloss:0.09405
[227]	train-mlogloss:0.16395	eval-mlogloss:0.09408
[228]	train-mlogloss:0.16395	eval-mlogloss:0.09407
[229]	train-mlogloss:0.16396	eval-mlogloss:0.09415
[230]	train-mlogloss:0.16397	eval-mlogloss:0.09416
[231]	train-mlogloss:0.16399	eval-mlogloss:0.09417
[232]	train-mlogloss:0.16397	eval-mlogloss:0.09418
[233]	train-mlogloss:0.16396	eval-mlogloss:0.09415
[234]	train-mlogloss:0.16398	eval-mlogloss:0.09423
[235]	train-mlogloss:0.16399	eval-mlogloss:0.09424
[236]	train-mlogloss:0.16399	eval-mlogloss:0.09428
[237]	train-mlogloss:0.16400	eval-mlogloss:0.09429
[238]	train-mlogloss:0.16386	eval-mlogloss:0.09428
[239]	train-mlogloss:0.16384	eval-mlogloss:0.09425
[240]	train-mlogloss:0.16384	eval-mlogloss:0.09429
[241]	train-mlogloss:0.16383	eval-mlogloss:0.09425
[242]	train-mlogloss:0.16383	eval-mlogloss:0.09427
[243]	train-mlogloss:0.16382	eval-mlogloss:0.09423
[244]	train-mlogloss:0.16383	eval-mlogloss:0.09424
[245]	train-mlogloss:0.16381	eval-mlogloss:0.09421
[246]	train-mlogloss:0.16380	eval-mlogloss:0.09414
[247]	train-mlogloss:0.16381	eval-mlogloss:0.09415
[248]	train-mlogloss:0.16381	eval-mlogloss:0.09414
[249]	train-mlogloss:0.16380	eval-mlogloss:0.09412
[250]	train-mlogloss:0.16380	eval-mlogloss:0.09407
[251]	train-mlogloss:0.16380	eval-mlogloss:0.09407
[252]	train-mlogloss:0.16371	eval-mlogloss:0.09394
[253]	train-mlogloss:0.16371	eval-mlogloss:0.09394
[254]	train-mlogloss:0.16371	eval-mlogloss:0.09397
[255]	train-mlogloss:0.16360	eval-mlogloss:0.09390
[256]	train-mlogloss:0.16360	eval-mlogloss:0.09389
[257]	train-mlogloss:0.16360	eval-mlogloss:0.09389
[258]	train-mlogloss:0.16360	eval-mlogloss:0.09385
[259]	train-mlogloss:0.16360	eval-mlogloss:0.09385
[260]	train-mlogloss:0.16360	eval-mlogloss:0.09384
[261]	train-mlogloss:0.16360	eval-mlogloss:0.09383
[262]	train-mlogloss:0.16357	eval-mlogloss:0.09353
[263]	train-mlogloss:0.16358	eval-mlogloss:0.09351
[264]	train-mlogloss:0.16344	eval-mlogloss:0.09325
[265]	train-mlogloss:0.16344	eval-mlogloss:0.09325
[266]	train-mlogloss:0.16341	eval-mlogloss:0.09293
[267]	train-mlogloss:0.16325	eval-mlogloss:0.09290
[268]	train-mlogloss:0.16310	eval-mlogloss:0.09264
[269]	train-mlogloss:0.16310	eval-mlogloss:0.09265
[270]	train-mlogloss:0.16310	eval-mlogloss:0.09263
[271]	train-mlogloss:0.16309	eval-mlogloss:0.09266
[272]	train-mlogloss:0.16309	eval-mlogloss:0.09268
[273]	train-mlogloss:0.16309	eval-mlogloss:0.09267
[274]	train-mlogloss:0.16309	eval-mlogloss:0.09264
[275]	train-mlogloss:0.16295	eval-mlogloss:0.09261
[276]	train-mlogloss:0.16295	eval-mlogloss:0.09260
[277]	train-mlogloss:0.16295	eval-mlogloss:0.09262
[278]	train-mlogloss:0.16283	eval-mlogloss:0.09239
[279]	train-mlogloss:0.16283	eval-mlogloss:0.09237
[280]	train-mlogloss:0.16233	eval-mlogloss:0.09155
[281]	train-mlogloss:0.16224	eval-mlogloss:0.09154
[282]	train-mlogloss:0.16221	eval-mlogloss:0.09157
[283]	train-mlogloss:0.16221	eval-mlogloss:0.09157
[284]	train-mlogloss:0.16221	eval-mlogloss:0.09159
[285]	train-mlogloss:0.16221	eval-mlogloss:0.09157
[286]	train-mlogloss:0.16220	eval-mlogloss:0.09161
[287]	train-mlogloss:0.16221	eval-mlogloss:0.09157
[288]	train-mlogloss:0.16213	eval-mlogloss:0.09154
[289]	train-mlogloss:0.16212	eval-mlogloss:0.09157
[290]	train-mlogloss:0.16204	eval-mlogloss:0.09156
[291]	train-mlogloss:0.16203	eval-mlogloss:0.09159
[292]	train-mlogloss:0.16203	eval-mlogloss:0.09161
[293]	train-mlogloss:0.16181	eval-mlogloss:0.09135
[294]	train-mlogloss:0.16169	eval-mlogloss:0.09134
[295]	train-mlogloss:0.16169	eval-mlogloss:0.09131
[296]	train-mlogloss:0.16169	eval-mlogloss:0.09137
[297]	train-mlogloss:0.16165	eval-mlogloss:0.09090
[298]	train-mlogloss:0.16165	eval-mlogloss:0.09090
[299]	train-mlogloss:0.16165	eval-mlogloss:0.09089

[I 2025-03-15 11:17:40,689] Trial 3 finished with value: 1.0 and parameters: {'lambda': 0.18321782303331988, 'alpha': 3.6246404894992376e-05, 'eta': 0.04216784591453224, 'gamma': 0.30655988987435706, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.5786240974626092, 'colsample_bytree': 0.7503553374850251}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.79641	eval-mlogloss:0.77068
[1]	train-mlogloss:0.60487	eval-mlogloss:0.56569

[I 2025-03-15 11:17:40,707] Trial 4 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08400	eval-mlogloss:1.08291
[1]	train-mlogloss:1.06974	eval-mlogloss:1.06835
[2]	train-mlogloss:1.05558	eval-mlogloss:1.05368
[3]	train-mlogloss:1.04155	eval-mlogloss:1.03950
[4]	train-mlogloss:1.02804	eval-mlogloss:1.02546
[5]	train-mlogloss:1.01454	eval-mlogloss:1.01113
[6]	train-mlogloss:1.00150	eval-mlogloss:0.99767
[7]	train-mlogloss:0.98892	eval-mlogloss:0.98486
[8]	train-mlogloss:0.97636	eval-mlogloss:0.97169
[9]	train-mlogloss:0.96410	eval-mlogloss:0.95888
[10]	train-mlogloss:0.95211	eval-mlogloss:0.94661
[11]	train-mlogloss:0.94019	eval-mlogloss:0.93388
[12]	train-mlogloss:0.92848	eval-mlogloss:0.92155
[13]	train-mlogloss:0.91697	eval-mlogloss:0.90944
[14]	train-mlogloss:0.90578	eval-mlogloss:0.89790
[15]	train-mlogloss:0.89475	eval-mlogloss:0.88646
[16]	train-mlogloss:0.88409	eval-mlogloss:0.87528
[17]	train-mlogloss:0.87335	eval-mlogloss:0.86432
[18]	train-mlogloss:0.86378	eval-mlogloss:0.85450
[19]	train-mlogloss:0.85336	eval-mlogloss:0.84356
[20]	train-mlogloss:0.84315	eval-mlogloss:0.83261
[21]	train-mlogloss:0.83290	eval-mlogloss:0.82188
[22]	train-mlogloss:0.82305	eval-mlogloss:0.81191
[23]	train-mlogloss:0.81325	eval-mlogloss:0.80174
[24]	train-mlogloss:0.80381	eval-mlogloss:0.79155
[25]	train-mlogloss:0.79441	eval-mlogloss:0.78139
[26]	train-mlogloss:0.78512	eval-mlogloss:0.77154
[27]	train-mlogloss:0.77611	eval-mlogloss:0.76202
[28]	train-mlogloss:0.76710	eval-mlogloss:0.75269
[29]	train-mlogloss:0.75833	eval-mlogloss:0.74345
[30]	train-mlogloss:0.74963	eval-mlogloss:0.73440
[31]	train-mlogloss:0.74098	eval-mlogloss:0.72529
[32]	train-mlogloss:0.73264	eval-mlogloss:0.71675
[33]	train-mlogloss:0.72452	eval-mlogloss:0.70808
[34]	train-mlogloss:0.71637	eval-mlogloss:0.69966
[35]	train-mlogloss:0.70849	eval-mlogloss:0.69115
[36]	train-mlogloss:0.70053	eval-mlogloss:0.68287
[37]	train-mlogloss:0.69275	eval-mlogloss:0.67490
[38]	train-mlogloss:0.68524	eval-mlogloss:0.66676
[39]	train-mlogloss:0.67767	eval-mlogloss:0.65903
[40]	train-mlogloss:0.67037	eval-mlogloss:0.65139
[41]	train-mlogloss:0.66298	eval-mlogloss:0.64365
[42]	train-mlogloss:0.65590	eval-mlogloss:0.63593
[43]	train-mlogloss:0.64886	eval-mlogloss:0.62855
[44]	train-mlogloss:0.64187	eval-mlogloss:0.62128
[45]	train-mlogloss:0.63495	eval-mlogloss:0.61400
[46]	train-mlogloss:0.62799	eval-mlogloss:0.60690
[47]	train-mlogloss:0.62126	eval-mlogloss:0.59999
[48]	train-mlogloss:0.61469	eval-mlogloss:0.59306
[49]	train-mlogloss:0.60830	eval-mlogloss:0.58625
[50]	train-mlogloss:0.60189	eval-mlogloss:0.57954
[51]	train-mlogloss:0.59585	eval-mlogloss:0.57309
[52]	train-mlogloss:0.58963	eval-mlogloss:0.56632
[53]	train-mlogloss:0.58361	eval-mlogloss:0.55992
[54]	train-mlogloss:0.57746	eval-mlogloss:0.55343
[55]	train-mlogloss:0.57139	eval-mlogloss:0.54713
[56]	train-mlogloss:0.56545	eval-mlogloss:0.54104
[57]	train-mlogloss:0.55955	eval-mlogloss:0.53480
[58]	train-mlogloss:0.55385	eval-mlogloss:0.52877
[59]	train-mlogloss:0.54828	eval-mlogloss:0.52304
[60]	train-mlogloss:0.54286	eval-mlogloss:0.51722
[61]	train-mlogloss:0.53731	eval-mlogloss:0.51156
[62]	train-mlogloss:0.53190	eval-mlogloss:0.50607
[63]	train-mlogloss:0.52663	eval-mlogloss:0.50030
[64]	train-mlogloss:0.52136	eval-mlogloss:0.49478
[65]	train-mlogloss:0.51615	eval-mlogloss:0.48934
[66]	train-mlogloss:0.51097	eval-mlogloss:0.48383
[67]	train-mlogloss:0.50590	eval-mlogloss:0.47831
[68]	train-mlogloss:0.50100	eval-mlogloss:0.47310
[69]	train-mlogloss:0.49615	eval-mlogloss:0.46816
[70]	train-mlogloss:0.49132	eval-mlogloss:0.46302
[71]	train-mlogloss:0.48655	eval-mlogloss:0.45792
[72]	train-mlogloss:0.48183	eval-mlogloss:0.45290
[73]	train-mlogloss:0.47713	eval-mlogloss:0.44804
[74]	train-mlogloss:0.47250	eval-mlogloss:0.44311
[75]	train-mlogloss:0.46803	eval-mlogloss:0.43842
[76]	train-mlogloss:0.46359	eval-mlogloss:0.43344
[77]	train-mlogloss:0.45916	eval-mlogloss:0.42855
[78]	train-mlogloss:0.45475	eval-mlogloss:0.42360
[79]	train-mlogloss:0.45046	eval-mlogloss:0.41890
[80]	train-mlogloss:0.44624	eval-mlogloss:0.41437
[81]	train-mlogloss:0.44196	eval-mlogloss:0.40997
[82]	train-mlogloss:0.43783	eval-mlogloss:0.40559
[83]	train-mlogloss:0.43377	eval-mlogloss:0.40131
[84]	train-mlogloss:0.42975	eval-mlogloss:0.39701
[85]	train-mlogloss:0.42583	eval-mlogloss:0.39269
[86]	train-mlogloss:0.42196	eval-mlogloss:0.38841
[87]	train-mlogloss:0.41811	eval-mlogloss:0.38417
[88]	train-mlogloss:0.41424	eval-mlogloss:0.37991
[89]	train-mlogloss:0.41036	eval-mlogloss:0.37590
[90]	train-mlogloss:0.40681	eval-mlogloss:0.37212
[91]	train-mlogloss:0.40310	eval-mlogloss:0.36811
[92]	train-mlogloss:0.39943	eval-mlogloss:0.36434
[93]	train-mlogloss:0.39587	eval-mlogloss:0.36054
[94]	train-mlogloss:0.39229	eval-mlogloss:0.35665
[95]	train-mlogloss:0.38896	eval-mlogloss:0.35301
[96]	train-mlogloss:0.38554	eval-mlogloss:0.34936
[97]	train-mlogloss:0.38222	eval-mlogloss:0.34579
[98]	train-mlogloss:0.37889	eval-mlogloss:0.34217
[99]	train-mlogloss:0.37572	eval-mlogloss:0.33878
[100]	train-mlogloss:0.37250	eval-mlogloss:0.33536
[101]	train-mlogloss:0.36953	eval-mlogloss:0.33214
[102]	train-mlogloss:0.36629	eval-mlogloss:0.32863
[103]	train-mlogloss:0.36312	eval-mlogloss:0.32519
[104]	train-mlogloss:0.35997	eval-mlogloss:0.32175
[105]	train-mlogloss:0.35720	eval-mlogloss:0.31862
[106]	train-mlogloss:0.35426	eval-mlogloss:0.31544
[107]	train-mlogloss:0.35155	eval-mlogloss:0.31226
[108]	train-mlogloss:0.34895	eval-mlogloss:0.30916
[109]	train-mlogloss:0.34606	eval-mlogloss:0.30612
[110]	train-mlogloss:0.34316	eval-mlogloss:0.30298
[111]	train-mlogloss:0.34061	eval-mlogloss:0.29998
[112]	train-mlogloss:0.33793	eval-mlogloss:0.29685
[113]	train-mlogloss:0.33541	eval-mlogloss:0.29390
[114]	train-mlogloss:0.33285	eval-mlogloss:0.29109
[115]	train-mlogloss:0.33041	eval-mlogloss:0.28830
[116]	train-mlogloss:0.32788	eval-mlogloss:0.28554
[117]	train-mlogloss:0.32528	eval-mlogloss:0.28262
[118]	train-mlogloss:0.32292	eval-mlogloss:0.28006
[119]	train-mlogloss:0.32053	eval-mlogloss:0.27744
[120]	train-mlogloss:0.31818	eval-mlogloss:0.27484
[121]	train-mlogloss:0.31573	eval-mlogloss:0.27211
[122]	train-mlogloss:0.31340	eval-mlogloss:0.26943
[123]	train-mlogloss:0.31144	eval-mlogloss:0.26745
[124]	train-mlogloss:0.30923	eval-mlogloss:0.26491
[125]	train-mlogloss:0.30707	eval-mlogloss:0.26257
[126]	train-mlogloss:0.30497	eval-mlogloss:0.26012
[127]	train-mlogloss:0.30285	eval-mlogloss:0.25796
[128]	train-mlogloss:0.30073	eval-mlogloss:0.25546
[129]	train-mlogloss:0.29856	eval-mlogloss:0.25314
[130]	train-mlogloss:0.29659	eval-mlogloss:0.25102
[131]	train-mlogloss:0.29449	eval-mlogloss:0.24853
[132]	train-mlogloss:0.29249	eval-mlogloss:0.24635
[133]	train-mlogloss:0.29068	eval-mlogloss:0.24421
[134]	train-mlogloss:0.28888	eval-mlogloss:0.24227
[135]	train-mlogloss:0.28703	eval-mlogloss:0.24007
[136]	train-mlogloss:0.28521	eval-mlogloss:0.23805
[137]	train-mlogloss:0.28326	eval-mlogloss:0.23599
[138]	train-mlogloss:0.28149	eval-mlogloss:0.23401
[139]	train-mlogloss:0.27962	eval-mlogloss:0.23195
[140]	train-mlogloss:0.27787	eval-mlogloss:0.23012
[141]	train-mlogloss:0.27616	eval-mlogloss:0.22810
[142]	train-mlogloss:0.27465	eval-mlogloss:0.22633
[143]	train-mlogloss:0.27297	eval-mlogloss:0.22463
[144]	train-mlogloss:0.27129	eval-mlogloss:0.22287
[145]	train-mlogloss:0.26974	eval-mlogloss:0.22119
[146]	train-mlogloss:0.26811	eval-mlogloss:0.21917
[147]	train-mlogloss:0.26642	eval-mlogloss:0.21712
[148]	train-mlogloss:0.26503	eval-mlogloss:0.21554
[149]	train-mlogloss:0.26343	eval-mlogloss:0.21378
[150]	train-mlogloss:0.26182	eval-mlogloss:0.21204
[151]	train-mlogloss:0.26050	eval-mlogloss:0.21056
[152]	train-mlogloss:0.25901	eval-mlogloss:0.20887
[153]	train-mlogloss:0.25743	eval-mlogloss:0.20707
[154]	train-mlogloss:0.25603	eval-mlogloss:0.20554
[155]	train-mlogloss:0.25454	eval-mlogloss:0.20417
[156]	train-mlogloss:0.25330	eval-mlogloss:0.20274
[157]	train-mlogloss:0.25202	eval-mlogloss:0.20124
[158]	train-mlogloss:0.25056	eval-mlogloss:0.19956
[159]	train-mlogloss:0.24918	eval-mlogloss:0.19797
[160]	train-mlogloss:0.24798	eval-mlogloss:0.19659
[161]	train-mlogloss:0.24661	eval-mlogloss:0.19503
[162]	train-mlogloss:0.24541	eval-mlogloss:0.19377
[163]	train-mlogloss:0.24424	eval-mlogloss:0.19252
[164]	train-mlogloss:0.24287	eval-mlogloss:0.19104
[165]	train-mlogloss:0.24158	eval-mlogloss:0.18965
[166]	train-mlogloss:0.24039	eval-mlogloss:0.18825
[167]	train-mlogloss:0.23922	eval-mlogloss:0.18702
[168]	train-mlogloss:0.23811	eval-mlogloss:0.18575
[169]	train-mlogloss:0.23697	eval-mlogloss:0.18454
[170]	train-mlogloss:0.23585	eval-mlogloss:0.18341
[171]	train-mlogloss:0.23470	eval-mlogloss:0.18204
[172]	train-mlogloss:0.23369	eval-mlogloss:0.18086
[173]	train-mlogloss:0.23260	eval-mlogloss:0.17960
[174]	train-mlogloss:0.23151	eval-mlogloss:0.17834
[175]	train-mlogloss:0.23048	eval-mlogloss:0.17725
[176]	train-mlogloss:0.22938	eval-mlogloss:0.17608
[177]	train-mlogloss:0.22838	eval-mlogloss:0.17503
[178]	train-mlogloss:0.22746	eval-mlogloss:0.17395
[179]	train-mlogloss:0.22644	eval-mlogloss:0.17289
[180]	train-mlogloss:0.22558	eval-mlogloss:0.17190
[181]	train-mlogloss:0.22450	eval-mlogloss:0.17067
[182]	train-mlogloss:0.22344	eval-mlogloss:0.16941
[183]	train-mlogloss:0.22253	eval-mlogloss:0.16840
[184]	train-mlogloss:0.22155	eval-mlogloss:0.16734
[185]	train-mlogloss:0.22059	eval-mlogloss:0.16624
[186]	train-mlogloss:0.21971	eval-mlogloss:0.16532
[187]	train-mlogloss:0.21882	eval-mlogloss:0.16435
[188]	train-mlogloss:0.21841	eval-mlogloss:0.16380
[189]	train-mlogloss:0.21761	eval-mlogloss:0.16285
[190]	train-mlogloss:0.21710	eval-mlogloss:0.16222
[191]	train-mlogloss:0.21671	eval-mlogloss:0.16162
[192]	train-mlogloss:0.21589	eval-mlogloss:0.16065
[193]	train-mlogloss:0.21506	eval-mlogloss:0.15970
[194]	train-mlogloss:0.21414	eval-mlogloss:0.15871
[195]	train-mlogloss:0.21331	eval-mlogloss:0.15781
[196]	train-mlogloss:0.21250	eval-mlogloss:0.15685
[197]	train-mlogloss:0.21213	eval-mlogloss:0.15636
[198]	train-mlogloss:0.21181	eval-mlogloss:0.15597
[199]	train-mlogloss:0.21145	eval-mlogloss:0.15559
[200]	train-mlogloss:0.21106	eval-mlogloss:0.15506
[201]	train-mlogloss:0.21026	eval-mlogloss:0.15404
[202]	train-mlogloss:0.20989	eval-mlogloss:0.15355
[203]	train-mlogloss:0.20955	eval-mlogloss:0.15309
[204]	train-mlogloss:0.20922	eval-mlogloss:0.15265
[205]	train-mlogloss:0.20895	eval-mlogloss:0.15228
[206]	train-mlogloss:0.20811	eval-mlogloss:0.15138
[207]	train-mlogloss:0.20776	eval-mlogloss:0.15097
[208]	train-mlogloss:0.20742	eval-mlogloss:0.15059
[209]	train-mlogloss:0.20709	eval-mlogloss:0.15016
[210]	train-mlogloss:0.20676	eval-mlogloss:0.14962
[211]	train-mlogloss:0.20644	eval-mlogloss:0.14927
[212]	train-mlogloss:0.20615	eval-mlogloss:0.14890
[213]	train-mlogloss:0.20587	eval-mlogloss:0.14850
[214]	train-mlogloss:0.20558	eval-mlogloss:0.14815
[215]	train-mlogloss:0.20523	eval-mlogloss:0.14770
[216]	train-mlogloss:0.20491	eval-mlogloss:0.14717
[217]	train-mlogloss:0.20457	eval-mlogloss:0.14672
[218]	train-mlogloss:0.20427	eval-mlogloss:0.14628
[219]	train-mlogloss:0.20403	eval-mlogloss:0.14598
[220]	train-mlogloss:0.20332	eval-mlogloss:0.14524
[221]	train-mlogloss:0.20304	eval-mlogloss:0.14487
[222]	train-mlogloss:0.20271	eval-mlogloss:0.14444
[223]	train-mlogloss:0.20238	eval-mlogloss:0.14399
[224]	train-mlogloss:0.20208	eval-mlogloss:0.14357
[225]	train-mlogloss:0.20176	eval-mlogloss:0.14316
[226]	train-mlogloss:0.20143	eval-mlogloss:0.14281
[227]	train-mlogloss:0.20113	eval-mlogloss:0.14249
[228]	train-mlogloss:0.20086	eval-mlogloss:0.14217
[229]	train-mlogloss:0.20053	eval-mlogloss:0.14183
[230]	train-mlogloss:0.20028	eval-mlogloss:0.14150
[231]	train-mlogloss:0.20005	eval-mlogloss:0.14124
[232]	train-mlogloss:0.19982	eval-mlogloss:0.14093
[233]	train-mlogloss:0.19950	eval-mlogloss:0.14050
[234]	train-mlogloss:0.19928	eval-mlogloss:0.14015
[235]	train-mlogloss:0.19908	eval-mlogloss:0.13989
[236]	train-mlogloss:0.19878	eval-mlogloss:0.13949
[237]	train-mlogloss:0.19848	eval-mlogloss:0.13906
[238]	train-mlogloss:0.19836	eval-mlogloss:0.13891
[239]	train-mlogloss:0.19812	eval-mlogloss:0.13856
[240]	train-mlogloss:0.19804	eval-mlogloss:0.13848
[241]	train-mlogloss:0.19777	eval-mlogloss:0.13811
[242]	train-mlogloss:0.19749	eval-mlogloss:0.13772
[243]	train-mlogloss:0.19747	eval-mlogloss:0.13771
[244]	train-mlogloss:0.19719	eval-mlogloss:0.13727
[245]	train-mlogloss:0.19689	eval-mlogloss:0.13685
[246]	train-mlogloss:0.19667	eval-mlogloss:0.13654
[247]	train-mlogloss:0.19640	eval-mlogloss:0.13617
[248]	train-mlogloss:0.19616	eval-mlogloss:0.13585
[249]	train-mlogloss:0.19594	eval-mlogloss:0.13553
[250]	train-mlogloss:0.19570	eval-mlogloss:0.13521
[251]	train-mlogloss:0.19542	eval-mlogloss:0.13476
[252]	train-mlogloss:0.19520	eval-mlogloss:0.13445
[253]	train-mlogloss:0.19517	eval-mlogloss:0.13443
[254]	train-mlogloss:0.19496	eval-mlogloss:0.13417
[255]	train-mlogloss:0.19474	eval-mlogloss:0.13388
[256]	train-mlogloss:0.19450	eval-mlogloss:0.13356
[257]	train-mlogloss:0.19447	eval-mlogloss:0.13354
[258]	train-mlogloss:0.19419	eval-mlogloss:0.13316
[259]	train-mlogloss:0.19395	eval-mlogloss:0.13283
[260]	train-mlogloss:0.19391	eval-mlogloss:0.13280
[261]	train-mlogloss:0.19372	eval-mlogloss:0.13250
[262]	train-mlogloss:0.19347	eval-mlogloss:0.13217
[263]	train-mlogloss:0.19345	eval-mlogloss:0.13209
[264]	train-mlogloss:0.19334	eval-mlogloss:0.13192
[265]	train-mlogloss:0.19330	eval-mlogloss:0.13190
[266]	train-mlogloss:0.19303	eval-mlogloss:0.13146
[267]	train-mlogloss:0.19277	eval-mlogloss:0.13112
[268]	train-mlogloss:0.19276	eval-mlogloss:0.13112
[269]	train-mlogloss:0.19252	eval-mlogloss:0.13080
[270]	train-mlogloss:0.19248	eval-mlogloss:0.13077
[271]	train-mlogloss:0.19227	eval-mlogloss:0.13042
[272]	train-mlogloss:0.19223	eval-mlogloss:0.13039
[273]	train-mlogloss:0.19202	eval-mlogloss:0.13010
[274]	train-mlogloss:0.19200	eval-mlogloss:0.13007
[275]	train-mlogloss:0.19177	eval-mlogloss:0.12976
[276]	train-mlogloss:0.19154	eval-mlogloss:0.12946
[277]	train-mlogloss:0.19129	eval-mlogloss:0.12914
[278]	train-mlogloss:0.19108	eval-mlogloss:0.12883
[279]	train-mlogloss:0.19095	eval-mlogloss:0.12866
[280]	train-mlogloss:0.19070	eval-mlogloss:0.12833
[281]	train-mlogloss:0.19061	eval-mlogloss:0.12822
[282]	train-mlogloss:0.19059	eval-mlogloss:0.12820
[283]	train-mlogloss:0.19055	eval-mlogloss:0.12819
[284]	train-mlogloss:0.19038	eval-mlogloss:0.12789
[285]	train-mlogloss:0.19029	eval-mlogloss:0.12769
[286]	train-mlogloss:0.19025	eval-mlogloss:0.12766
[287]	train-mlogloss:0.19001	eval-mlogloss:0.12740
[288]	train-mlogloss:0.18996	eval-mlogloss:0.12738
[289]	train-mlogloss:0.18988	eval-mlogloss:0.12727
[290]	train-mlogloss:0.18985	eval-mlogloss:0.12726
[291]	train-mlogloss:0.18964	eval-mlogloss:0.12698
[292]	train-mlogloss:0.18959	eval-mlogloss:0.12695
[293]	train-mlogloss:0.18938	eval-mlogloss:0.12667
[294]	train-mlogloss:0.18912	eval-mlogloss:0.12632
[295]	train-mlogloss:0.18909	eval-mlogloss:0.12629
[296]	train-mlogloss:0.18889	eval-mlogloss:0.12604
[297]	train-mlogloss:0.18887	eval-mlogloss:0.12596
[298]	train-mlogloss:0.18870	eval-mlogloss:0.12574
[299]	train-mlogloss:0.18869	eval-mlogloss:0.12573

[I 2025-03-15 11:17:43,705] Trial 5 finished with value: 1.0 and parameters: {'lambda': 1.7500169632070086e-07, 'alpha': 0.019185698211234257, 'eta': 0.011198828304029297, 'gamma': 1.2059458999898164e-08, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8763598549716616, 'colsample_bytree': 0.826600247761123}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.88878	eval-mlogloss:0.87117

[I 2025-03-15 11:17:43,717] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00943	eval-mlogloss:1.01314

[I 2025-03-15 11:17:43,723] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.78634	eval-mlogloss:0.75806
[1]	train-mlogloss:0.59013	eval-mlogloss:0.54516

[I 2025-03-15 11:17:43,732] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92434	eval-mlogloss:0.91148
[1]	train-mlogloss:0.71720	eval-mlogloss:0.68868

[I 2025-03-15 11:17:43,745] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96925	eval-mlogloss:0.96642

[I 2025-03-15 11:17:43,778] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87389	eval-mlogloss:0.88008
[1]	train-mlogloss:0.67224	eval-mlogloss:0.65957

[I 2025-03-15 11:17:43,810] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85573	eval-mlogloss:0.85820
[1]	train-mlogloss:0.63925	eval-mlogloss:0.62405

[I 2025-03-15 11:17:43,845] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03835	eval-mlogloss:1.04070
[1]	train-mlogloss:0.89574	eval-mlogloss:0.89110
[2]	train-mlogloss:0.77815	eval-mlogloss:0.76674
[3]	train-mlogloss:0.70513	eval-mlogloss:0.68448

[I 2025-03-15 11:17:43,887] Trial 13 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.82293	eval-mlogloss:0.80477

[I 2025-03-15 11:17:43,918] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87562	eval-mlogloss:0.86901
[1]	train-mlogloss:0.67304	eval-mlogloss:0.64969

[I 2025-03-15 11:17:43,956] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92270	eval-mlogloss:0.91977
[1]	train-mlogloss:0.72696	eval-mlogloss:0.71238

[I 2025-03-15 11:17:43,987] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87227	eval-mlogloss:0.87657

[I 2025-03-15 11:17:44,021] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.93835	eval-mlogloss:0.92774

[I 2025-03-15 11:17:44,053] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03501	eval-mlogloss:1.03069
[1]	train-mlogloss:0.94490	eval-mlogloss:0.93617
[2]	train-mlogloss:0.86523	eval-mlogloss:0.85328
[3]	train-mlogloss:0.79367	eval-mlogloss:0.78053
[4]	train-mlogloss:0.73102	eval-mlogloss:0.71606

[I 2025-03-15 11:17:44,089] Trial 19 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.83730	eval-mlogloss:0.88526

[I 2025-03-15 11:17:44,120] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00025	eval-mlogloss:1.00795

[I 2025-03-15 11:17:44,164] Trial 21 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00686	eval-mlogloss:1.00640

[I 2025-03-15 11:17:44,206] Trial 22 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97286	eval-mlogloss:0.97880

[I 2025-03-15 11:17:44,251] Trial 23 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89474	eval-mlogloss:0.88840

[I 2025-03-15 11:17:44,299] Trial 24 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.98004	eval-mlogloss:0.96792
[1]	train-mlogloss:0.72112	eval-mlogloss:0.69432

[I 2025-03-15 11:17:44,346] Trial 25 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.94774	eval-mlogloss:0.94047

[I 2025-03-15 11:17:44,392] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02170	eval-mlogloss:1.02846
[1]	train-mlogloss:0.86331	eval-mlogloss:0.85736
[2]	train-mlogloss:0.73819	eval-mlogloss:0.72159
[3]	train-mlogloss:0.66222	eval-mlogloss:0.63315
[4]	train-mlogloss:0.59142	eval-mlogloss:0.55918

[I 2025-03-15 11:17:44,451] Trial 27 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.81863	eval-mlogloss:0.79914
[1]	train-mlogloss:0.63271	eval-mlogloss:0.60684

[I 2025-03-15 11:17:44,495] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.90030	eval-mlogloss:0.86941

[I 2025-03-15 11:17:44,539] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89532	eval-mlogloss:0.89427

[I 2025-03-15 11:17:44,587] Trial 30 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04902	eval-mlogloss:1.04608
[1]	train-mlogloss:1.00769	eval-mlogloss:1.00273
[2]	train-mlogloss:0.96337	eval-mlogloss:0.95670
[3]	train-mlogloss:0.92021	eval-mlogloss:0.91161
[4]	train-mlogloss:0.88099	eval-mlogloss:0.87164
[5]	train-mlogloss:0.84287	eval-mlogloss:0.83167
[6]	train-mlogloss:0.80731	eval-mlogloss:0.79460
[7]	train-mlogloss:0.77599	eval-mlogloss:0.76107
[8]	train-mlogloss:0.74581	eval-mlogloss:0.72876
[9]	train-mlogloss:0.71669	eval-mlogloss:0.69753
[10]	train-mlogloss:0.68978	eval-mlogloss:0.66811
[11]	train-mlogloss:0.66333	eval-mlogloss:0.63909
[12]	train-mlogloss:0.63858	eval-mlogloss:0.61301
[13]	train-mlogloss:0.61531	eval-mlogloss:0.58810
[14]	train-mlogloss:0.59230	eval-mlogloss:0.56377
[15]	train-mlogloss:0.57051	eval-mlogloss:0.54106

[I 2025-03-15 11:17:44,667] Trial 31 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.00963	eval-mlogloss:1.00266
[1]	train-mlogloss:0.93094	eval-mlogloss:0.91936
[2]	train-mlogloss:0.85879	eval-mlogloss:0.84319
[3]	train-mlogloss:0.79330	eval-mlogloss:0.77611

[I 2025-03-15 11:17:44,737] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04976	eval-mlogloss:1.04674
[1]	train-mlogloss:1.00348	eval-mlogloss:0.99779
[2]	train-mlogloss:0.96026	eval-mlogloss:0.95310
[3]	train-mlogloss:0.91772	eval-mlogloss:0.90916

[I 2025-03-15 11:17:44,790] Trial 33 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08030	eval-mlogloss:1.07894
[1]	train-mlogloss:1.06253	eval-mlogloss:1.06078
[2]	train-mlogloss:1.04499	eval-mlogloss:1.04259
[3]	train-mlogloss:1.02768	eval-mlogloss:1.02508
[4]	train-mlogloss:1.01109	eval-mlogloss:1.00782
[5]	train-mlogloss:0.99459	eval-mlogloss:0.99023
[6]	train-mlogloss:0.97870	eval-mlogloss:0.97384
[7]	train-mlogloss:0.96335	eval-mlogloss:0.95816
[8]	train-mlogloss:0.94819	eval-mlogloss:0.94215
[9]	train-mlogloss:0.93350	eval-mlogloss:0.92677
[10]	train-mlogloss:0.91905	eval-mlogloss:0.91195
[11]	train-mlogloss:0.90490	eval-mlogloss:0.89699
[12]	train-mlogloss:0.89102	eval-mlogloss:0.88235
[13]	train-mlogloss:0.87738	eval-mlogloss:0.86781
[14]	train-mlogloss:0.86425	eval-mlogloss:0.85415
[15]	train-mlogloss:0.85132	eval-mlogloss:0.84070

[I 2025-03-15 11:17:44,860] Trial 34 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:0.75357	eval-mlogloss:0.72479

[I 2025-03-15 11:17:44,908] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.90530	eval-mlogloss:0.89116

[I 2025-03-15 11:17:44,948] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.78026	eval-mlogloss:0.75790

[I 2025-03-15 11:17:44,987] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92214	eval-mlogloss:0.91756
[1]	train-mlogloss:0.74107	eval-mlogloss:0.72708

[I 2025-03-15 11:17:45,029] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01530	eval-mlogloss:1.00452
[1]	train-mlogloss:0.89804	eval-mlogloss:0.88206
[2]	train-mlogloss:0.80219	eval-mlogloss:0.78008
[3]	train-mlogloss:0.71449	eval-mlogloss:0.68766

[I 2025-03-15 11:17:45,077] Trial 39 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.78036	eval-mlogloss:0.75793

[I 2025-03-15 11:17:45,167] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07585	eval-mlogloss:1.07398
[1]	train-mlogloss:1.05403	eval-mlogloss:1.05178
[2]	train-mlogloss:1.03243	eval-mlogloss:1.02927
[3]	train-mlogloss:1.01138	eval-mlogloss:1.00741
[4]	train-mlogloss:0.99111	eval-mlogloss:0.98622
[5]	train-mlogloss:0.97157	eval-mlogloss:0.96618
[6]	train-mlogloss:0.95254	eval-mlogloss:0.94633
[7]	train-mlogloss:0.93412	eval-mlogloss:0.92747
[8]	train-mlogloss:0.91615	eval-mlogloss:0.90863
[9]	train-mlogloss:0.89861	eval-mlogloss:0.89025
[10]	train-mlogloss:0.88136	eval-mlogloss:0.87224
[11]	train-mlogloss:0.86460	eval-mlogloss:0.85494
[12]	train-mlogloss:0.84850	eval-mlogloss:0.83816
[13]	train-mlogloss:0.83274	eval-mlogloss:0.82162
[14]	train-mlogloss:0.81738	eval-mlogloss:0.80571
[15]	train-mlogloss:0.80246	eval-mlogloss:0.78975
[16]	train-mlogloss:0.78806	eval-mlogloss:0.77461

[I 2025-03-15 11:17:45,295] Trial 41 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.04169	eval-mlogloss:1.03780
[1]	train-mlogloss:0.98982	eval-mlogloss:0.98299
[2]	train-mlogloss:0.94096	eval-mlogloss:0.93210
[3]	train-mlogloss:0.89486	eval-mlogloss:0.88537
[4]	train-mlogloss:0.85254	eval-mlogloss:0.84266

[I 2025-03-15 11:17:45,362] Trial 42 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02202	eval-mlogloss:1.01617
[1]	train-mlogloss:0.95221	eval-mlogloss:0.94456
[2]	train-mlogloss:0.88916	eval-mlogloss:0.88035
[3]	train-mlogloss:0.83227	eval-mlogloss:0.82238

[I 2025-03-15 11:17:45,456] Trial 43 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.01669	eval-mlogloss:1.02042

[I 2025-03-15 11:17:45,609] Trial 44 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06064	eval-mlogloss:1.05780
[1]	train-mlogloss:1.02459	eval-mlogloss:1.02162
[2]	train-mlogloss:0.98998	eval-mlogloss:0.98465
[3]	train-mlogloss:0.95630	eval-mlogloss:0.95038
[4]	train-mlogloss:0.92512	eval-mlogloss:0.91760
[5]	train-mlogloss:0.89487	eval-mlogloss:0.88567
[6]	train-mlogloss:0.86640	eval-mlogloss:0.85623
[7]	train-mlogloss:0.83961	eval-mlogloss:0.82897
[8]	train-mlogloss:0.81393	eval-mlogloss:0.80255
[9]	train-mlogloss:0.78910	eval-mlogloss:0.77590
[10]	train-mlogloss:0.76529	eval-mlogloss:0.75118
[11]	train-mlogloss:0.74249	eval-mlogloss:0.72743
[12]	train-mlogloss:0.72115	eval-mlogloss:0.70455
[13]	train-mlogloss:0.70003	eval-mlogloss:0.68248
[14]	train-mlogloss:0.68001	eval-mlogloss:0.66223
[15]	train-mlogloss:0.66039	eval-mlogloss:0.64108

[I 2025-03-15 11:17:45,691] Trial 45 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.06180	eval-mlogloss:1.06266
[1]	train-mlogloss:1.01325	eval-mlogloss:1.00842
[2]	train-mlogloss:0.96215	eval-mlogloss:0.95748
[3]	train-mlogloss:0.90777	eval-mlogloss:0.90003

[I 2025-03-15 11:17:45,771] Trial 46 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.89362	eval-mlogloss:0.89226

[I 2025-03-15 11:17:45,835] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99423	eval-mlogloss:0.98808

[I 2025-03-15 11:17:46,037] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99633	eval-mlogloss:0.99518
[1]	train-mlogloss:0.86510	eval-mlogloss:0.85683

[I 2025-03-15 11:17:46,090] Trial 49 pruned. Trial was pruned at iteration 1.

Best trial: {'lambda': 5.267681949269602e-05, 'alpha': 0.004725237220231881, 'eta': 0.2969689082106233, 'gamma': 0.0004521341175623526, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.5595932231896997, 'colsample_bytree': 0.8801714611501971}
Best accuracy: 1.0

In [45]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()

---