
---

# 🏷️ **`Feature Encoding with Python in ML for Data Science`** 📊  

**Feature Encoding** is a critical step in **Machine Learning (ML)**, where categorical variables are converted into numerical format. Many ML models, such as **Linear Regression, Decision Trees, and Neural Networks**, require numerical input, making **feature encoding essential**.

---

## ✅ **1. Why is Feature Encoding Important?**  

✔ **Handles categorical data** → ML models can only process numbers.  
✔ **Improves model interpretability** → Numeric features are easier to analyze.  
✔ **Enhances model performance** → Proper encoding avoids misleading relationships.  
✔ **Prevents bias** → Incorrect encoding can cause some categories to dominate others.  

---

## 🏷️ **2. Types of Feature Encoding in ML**  

| **Encoding Type**           | **When to Use**                         | **Common Algorithms**              |
|-----------------------------|-----------------------------------------|------------------------------------|
| **Label Encoding**          | Ordinal data (ranked categories)        | Decision Trees, Random Forest     |
| **One-Hot Encoding**        | Nominal data (unordered categories)     | Linear Regression, Neural Networks |
| **Ordinal Encoding**        | Categorical features with clear order   | Regression, Decision Trees        |
| **Frequency Encoding**      | Large categorical data (high cardinality) | Tree-based models (XGBoost, RF)   |
| **Binary Encoding**         | Large categorical data (reduces dimension) | Random Forest, SVM, XGBoost       |
| **Target Encoding**         | When categories have numerical correlation | Regression, Bayesian models       |

---

## 🔢 **3. Label Encoding (Integer Encoding)**  

**Description:**  
- Converts **categorical values** into **integer labels** (e.g., `Low = 0`, `Medium = 1`, `High = 2`).  
- Used for **ordinal features** (where order matters).  
- **⚠️ Warning:** Can create **false numerical relationships** in **nominal** data.  

### ✍️ **Example: Applying Label Encoding in Python**

In [1]:

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Sample Data
df = pd.DataFrame({'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']})

# Apply Label Encoding
label_encoder = LabelEncoder()
df['Education_Label'] = label_encoder.fit_transform(df['Education'])

print(df)

     Education  Education_Label
0  High School                1
1     Bachelor                0
2       Master                2
3          PhD                3
4     Bachelor                0
5       Master                2


**✅ Best For:** Ordinal categories like **Education Level, Customer Satisfaction, Ratings.**  
**❌ Avoid For:** Nominal categories like **Colors, Cities, Products.**  

---

## 🏷️ **4. One-Hot Encoding (OHE)**  

**Description:**  
- Converts **categorical values** into **binary (0/1) columns**.  
- Prevents **false ordinal relationships** caused by Label Encoding.  
- Increases **dimensionality** (can cause issues with high-cardinality data).  

### ✍️ **Example: Applying One-Hot Encoding in Python**

In [2]:

# Apply One-Hot Encoding
df_ohe = pd.get_dummies(df, columns=['Education'], prefix='Edu')
print(df_ohe)

   Education_Label  Edu_Bachelor  Edu_High School  Edu_Master  Edu_PhD
0                1         False             True       False    False
1                0          True            False       False    False
2                2         False            False        True    False
3                3         False            False       False     True
4                0          True            False       False    False
5                2         False            False        True    False


**✅ Best For:** Nominal data (unordered categories like **Colors, Cities, Gender**).  
**❌ Avoid If:** High-cardinality (many unique values like **ZIP codes, Product IDs**).  

---

## 🔢 **5. Ordinal Encoding (For Ordered Categories)**  

**Description:**  
- Assigns **increasing integers** to categories based on ranking.  
- Used when categories have a **natural order**.  

### ✍️ **Example: Applying Ordinal Encoding in Python**

In [3]:

from sklearn.preprocessing import OrdinalEncoder

# Define Ordered Categories
edu_order = [['High School', 'Bachelor', 'Master', 'PhD']]

# Apply Ordinal Encoding
ordinal_encoder = OrdinalEncoder(categories=edu_order)
df['Education_Ordinal'] = ordinal_encoder.fit_transform(df[['Education']])

print(df)

     Education  Education_Label  Education_Ordinal
0  High School                1                0.0
1     Bachelor                0                1.0
2       Master                2                2.0
3          PhD                3                3.0
4     Bachelor                0                1.0
5       Master                2                2.0


**✅ Best For:** Data with a clear ranking (e.g., **Small, Medium, Large**).  
**❌ Avoid For:** Nominal categories (**Colors, Cities, Product Names**).  

---

## 🔢 **6. Frequency Encoding (Count Encoding)**  

**Description:**  
- Replaces categories with their **frequency (count)** in the dataset.  
- Works well with **tree-based models (XGBoost, Random Forest)**.  

### ✍️ **Example: Applying Frequency Encoding in Python**

In [4]:

# Frequency Encoding
df['Education_Freq'] = df['Education'].map(df['Education'].value_counts())
print(df)

     Education  Education_Label  Education_Ordinal  Education_Freq
0  High School                1                0.0               1
1     Bachelor                0                1.0               2
2       Master                2                2.0               2
3          PhD                3                3.0               1
4     Bachelor                0                1.0               2
5       Master                2                2.0               2


**✅ Best For:** Large categorical datasets (**Customer Segments, Products**).  
**❌ Avoid If:** The frequency distribution is **imbalanced**.  

---

## 🔢 **7. Binary Encoding (For High-Cardinality Data)**  

**Description:**  
- Converts categories into **binary digits (0/1)**.  
- Reduces dimensionality compared to **One-Hot Encoding**.  

### ✍️ **Example: Applying Binary Encoding in Python**

In [7]:

from category_encoders import BinaryEncoder

# Apply Binary Encoding
binary_encoder = BinaryEncoder(cols=['Education'])
df_binary = binary_encoder.fit_transform(df)

print(df_binary)

   Education_0  Education_1  Education_2  Education_Label  Education_Ordinal  \
0            0            0            1                1                0.0
1            0            1            0                0                1.0
2            0            1            1                2                2.0
3            1            0            0                3                3.0
4            0            1            0                0                1.0
5            0            1            1                2                2.0

   Education_Freq
0               1
1               2
2               2
3               1
4               2
5               2



**✅ Best For:** Large categorical features (**Countries, ZIP Codes**).  
**❌ Avoid If:** Only a few unique values (better to use OHE).  

---

## 🔢 **8. Target Encoding (Mean Encoding)**  

**Description:**  
- Replaces categories with their **mean target value** (for regression/classification).  
- Used in **Bayesian models, Tree-based models**.  

### ✍️ **Example: Applying Target Encoding in Python**

In [8]:

from category_encoders import TargetEncoder

# Sample Data
df_target = pd.DataFrame({'City': ['New York', 'LA', 'Chicago', 'LA', 'New York'],
                          'Sales': [100, 200, 150, 180, 110]})

# Apply Target Encoding
target_encoder = TargetEncoder(cols=['City'])
df_target['City_TargetEnc'] = target_encoder.fit_transform(df_target['City'], df_target['Sales'])

print(df_target)

       City  Sales  City_TargetEnc
0  New York    100      141.900404
1        LA    200      153.957745
2   Chicago    150      148.260217
3        LA    180      153.957745
4  New York    110      141.900404

**✅ Best For:** Regression problems, categorical variables with strong correlation.  
**❌ Avoid If:** High risk of **data leakage** (only use in cross-validation).  

---

## 🎯 **9. Choosing the Right Encoding Method**  

| **Scenario**                    | **Recommended Encoding** |
|----------------------------------|--------------------------|
| **Ordinal data (e.g., Ratings)** | **Ordinal Encoding**      |
| **Nominal data (few categories)** | **One-Hot Encoding**     |
| **High-cardinality categorical** | **Binary / Frequency Encoding** |
| **Tree-based models (XGBoost, RF)** | **Target / Frequency Encoding** |
| **Regression models**            | **Target Encoding**      |

---

## 🏆 **10. Final Thoughts**  

✔ **Encoding categorical data properly ensures better ML model performance.**  
✔ **Use One-Hot Encoding for nominal data** and **Ordinal Encoding for ranked data.**  
✔ **For high-cardinality features, use Frequency or Binary Encoding.**  
✔ **Avoid Target Encoding on raw data (risk of leakage).**  

💡 **Pro Tip:** Always analyze **feature importance** after encoding to avoid redundant columns.

---

## ***`Further Practice`***

In [13]:
# import libraries
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    OrdinalEncoder,
)

In [12]:
# load data
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### ***`LabelEncoder`***

In [17]:
# encode time with label encoder 
le = LabelEncoder()

df['l_encoded_time'] = le.fit_transform(df['time'])

print(df[['time', 'l_encoded_time']].sample(10))

       time  l_encoded_time
101  Dinner               0
84    Lunch               1
87    Lunch               1
103  Dinner               0
125   Lunch               1
45   Dinner               0
86    Lunch               1
34   Dinner               0
77    Lunch               1
7    Dinner               0

#### ***`OrdinalEncoder`***

In [19]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [21]:
# encode time with ordinal encoder 
oe = OrdinalEncoder(categories=[['Sat','Sun','Thur','Fri']])

df['oe_encoded_day'] = oe.fit_transform(df[['day']])

print(df[['day', 'oe_encoded_day']].sample(10))

      day  oe_encoded_day
41    Sun             1.0
25    Sat             0.0
7     Sun             1.0
196  Thur             2.0
154   Sun             1.0
97    Fri             3.0
179   Sun             1.0
200  Thur             2.0
106   Sat             0.0
114   Sun             1.0

#### ***`OneHotEncoder`***

In [23]:
# encode time with one hot encoder 
ohe = OneHotEncoder()

ohe_encoded_day = ohe.fit_transform(df[['day']]).toarray()
df[ohe.categories_[0]] = ohe_encoded_day

print(df[['day'] + list(ohe.categories_[0])].sample(10))

      day  Fri  Sat  Sun  Thur
37    Sat  0.0  1.0  0.0   0.0
36    Sat  0.0  1.0  0.0   0.0
183   Sun  0.0  0.0  1.0   0.0
151   Sun  0.0  0.0  1.0   0.0
91    Fri  1.0  0.0  0.0   0.0
228   Sat  0.0  1.0  0.0   0.0
83   Thur  0.0  0.0  0.0   1.0
10    Sun  0.0  0.0  1.0   0.0
31    Sat  0.0  1.0  0.0   0.0
29    Sat  0.0  1.0  0.0   0.0

#### ***`BinaryEncoder`***

In [26]:
from category_encoders import BinaryEncoder

binary_encoder = BinaryEncoder()

df_binary = binary_encoder.fit_transform(df['day'])

df_binary.sample(10)

     day_0  day_1  day_2
144      0      1      1
36       0      1      0
229      0      1      0
163      0      0      1
221      1      0      0
38       0      1      0
234      0      1      0
127      0      1      1
54       0      0      1
116      0      0      1

----