
---

# 🔄 ***`Encoding and Inverse Transformation in Machine Learning for Data Science`***  

---

## ✅ **Introduction**  
📌 **Encoding** is the process of converting **categorical data** into a numerical format so that machine learning models can interpret it.  
📌 **Inverse Transformation** is the process of converting encoded data **back to its original form** for better interpretation of model results.  

✅ Essential for handling **categorical data** in ML models.  
✅ Required when models like **Logistic Regression**, **SVM**, and **KNN** cannot process text directly.  
✅ Inverse transformation helps in **interpreting model predictions** accurately.  

---

## 🔎 **1. Why Encoding is Necessary?**  
ML models work with **numerical data** — categorical features must be encoded to:

✅ Improve model performance.  
✅ Ensure compatibility with ML algorithms.  
✅ Handle **ordinal** and **nominal** data effectively.  

---

## 📊 **2. Types of Encoding Techniques**  

### 🔹 **1. Label Encoding**
- Assigns a **unique integer** to each category.  
- Efficient for **ordinal data** (where order matters).  
- No new columns are created.  

**Example:**  
```
Color → [Red, Green, Blue]  
Label Encoded → [0, 1, 2]
```

✅ Simple and memory-efficient.  
❗ May introduce **misleading relationships** for **nominal data**.  

---

### 🔹 **2. One-Hot Encoding**
- Creates a **new binary column** for each category.  
- Suitable for **nominal data** (where order doesn’t matter).  

**Example:**  
```
Color → [Red, Green, Blue]  
One-Hot Encoded → [Red → 1 0 0], [Green → 0 1 0], [Blue → 0 0 1]
```

✅ Prevents misleading numerical relationships.  
❗ May increase dimensionality with many categories (**curse of dimensionality**).  

---

### 🔹 **3. Ordinal Encoding**
- Encodes categorical data with **integer values** while respecting the **order**.  

**Example:**  
```
Size → [Small, Medium, Large]  
Ordinal Encoded → [0, 1, 2]
```

✅ Best suited for **ordinal features** with natural order.  
❗ May confuse the model if used on **nominal data**.  

---

### 🔹 **4. Target Encoding (Mean Encoding)**
- Replaces each category with the **mean of the target variable** for that category.  

**Example:**  
```
City   → [New York, LA, Chicago]  
Target → [500, 300, 400]  
Target Encoded → [0.5, 0.3, 0.4]
```

✅ Ideal for **high-cardinality** categorical data.  
❗ Risk of **data leakage** — should only be done on the **training set**.

---

### 🔹 **5. Frequency Encoding**
- Replaces each category with its **frequency** in the dataset.  

**Example:**  
```
Color → [Red, Green, Green, Blue, Red, Red]  
Frequency Encoded → [3, 2, 1]
```

✅ Efficient for large datasets with **many unique categories**.  
❗ Risk of model bias if frequencies vary significantly.  

---

### 🔹 **6. Binary Encoding**
- Converts categories into **binary values** and then splits each binary digit into separate columns.  

**Example:**  
```
Category → [A, B, C]  
Binary Encoded → [001, 010, 011]
```

✅ Reduces dimensionality compared to One-Hot Encoding.  
❗ May be less interpretable.  

---

## 🔄 **3. Inverse Transformation**  
📌 Inverse transformation is essential to **convert encoded data back to its original form** for better interpretation.  

✅ Helps interpret model results in **human-readable** format.  
✅ Ensures easier insights and improved reporting.  

---

### 📋 **Python Example: Encoding & Inverse Transformation**

**Step 1: Encode Data Using `LabelEncoder`**

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Sample Data
data = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Red', 'Blue']
})

# Encoding
encoder = LabelEncoder()
data['Color_encoded'] = encoder.fit_transform(data['Color'])

print("Encoded Data:\n", data)

# Inverse Transformation
data['Color_decoded'] = encoder.inverse_transform(data['Color_encoded'])
print("\nInverse Transformed Data:\n", data)

Encoded Data:
    Color  Color_encoded
0    Red              2
1  Green              1
2   Blue              0
3    Red              2
4   Blue              0

Inverse Transformed Data:
    Color  Color_encoded Color_decoded
0    Red              2           Red
1  Green              1         Green
2   Blue              0          Blue
3    Red              2           Red
4   Blue              0          Blue


---

### 📋 **Example: One-Hot Encoding with Inverse Transformation**

**Step 1: Encode Data Using `OneHotEncoder`**

In [4]:
from sklearn.preprocessing import OneHotEncoder

# Sample Data
data = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red', 'Blue']})

# One-Hot Encoding
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data[['Color']])

# Create Encoded DataFrame
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['Color']))

# Inverse Transformation
inverse_transformed = encoder.inverse_transform(encoded_data)

print("\nEncoded Data:\n", encoded_df)
print("\nInverse Transformed Data:\n", inverse_transformed)

Encoded Data:
    Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

Inverse Transformed Data:
 [['Red']
 ['Green']
 ['Blue']
 ['Red']
 ['Blue']]

---

### 📋 **Example: Target Encoding (with Data Leakage Prevention)**

In [1]:
import pandas as pd
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split

# Sample Data
data = pd.DataFrame({
    'City': ['NY', 'LA', 'Chicago', 'NY', 'LA'],
    'Price': [500, 300, 400, 600, 350]
})

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    data[['City']], data['Price'], test_size=0.3, random_state=42
)

# Target Encoding (on Training Set Only)
encoder = TargetEncoder()
X_train_encoded = encoder.fit_transform(X_train, y_train)
X_test_encoded = encoder.transform(X_test)

print("Encoded Training Data:\n", X_train_encoded)
print("\nEncoded Test Data:\n", X_test_encoded)

Encoded Training Data:
          City
2  486.989153
0  507.092553
3  507.092553

Encoded Test Data:
     City
1  500.0
4  500.0


---

## ⚠️ **4. Key Considerations for Encoding & Inverse Transformation**  

✅ **Label Encoding** works best for **ordinal data** with meaningful order.  
✅ **One-Hot Encoding** is ideal for **nominal data** but may increase dimensionality.  
✅ **Target Encoding** is powerful but can lead to **data leakage** if improperly applied.  
✅ **Inverse Transformation** is crucial for interpreting encoded results in real-world applications.  

---

## 🔥 **5. Best Practices for Encoding Data**  

✅ Always apply **inverse transformation** after model prediction to understand the output.  
✅ Use **`fit()`** only on the **training data** and **`transform()`** on **test data** to avoid data leakage.  
✅ For **large datasets** with high cardinality, prefer **Target Encoding** or **Frequency Encoding**.  
✅ Apply **feature scaling** (e.g., `StandardScaler`) after encoding continuous features.  

---

## 🏆 **6. Key Takeaways**  

✔️ **Encoding** is crucial for converting categorical data into numerical form for ML models.  
✔️ **Inverse Transformation** ensures model predictions are easily interpretable.  
✔️ Choose the right encoding method based on data type:  
   - **Label Encoding** → For **ordinal data**.  
   - **One-Hot Encoding** → For **nominal data**.  
   - **Target Encoding** → For **high-cardinality** features.  
✔️ Always apply **inverse transformation** before final reporting or insights.

💡 **Pro Tip:** Use **`ColumnTransformer`** in pipelines to efficiently apply different encodings to different features.

---

## ***`Further Practice`***

In [1]:
# import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    OrdinalEncoder,
    StandardScaler,
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
# load the data
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
# impute the missing values
df['age'].fillna(df['age'].median(),inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

# drop deck column
df.drop('deck',axis=1,inplace=True)

In [ ]:
# encode all categorical variables and object variables using LabelEncoder()

le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_class = LabelEncoder()
le_who = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['class'] = le_class.fit_transform(df['class'])
df['who'] = le_who.fit_transform(df['who'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [5]:
df.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
837,0,3,1,28.0,0,0,8.0500,2,2,1,True,2,0,True
641,1,1,0,24.0,0,0,69.3000,0,0,2,False,0,1,True
801,1,2,0,31.0,1,1,26.2500,2,1,2,False,2,1,False
817,0,2,1,31.0,1,1,37.0042,0,1,1,True,0,0,False
823,1,3,0,27.0,0,1,12.4750,2,2,2,False,2,1,False

In [6]:
# inverse transform the data

df['sex'] = le_sex.inverse_transform(df['sex'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['class'] = le_class.inverse_transform(df['class'])
df['who'] = le_who.inverse_transform(df['who'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [9]:
# encode all categorical variables and object variables using OneHotEncoder()
df = sns.load_dataset('titanic')

cat_columns = ['sex', 'embarked']

encoder = OneHotEncoder()
encoded_df = pd.DataFrame(encoder.fit_transform(df[cat_columns]))

# concatenate the dataframes 
df = pd.concat([df, encoded_df], axis=1)
# df.drop(cat_columns, axis=1, inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,0
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,"(0, 1)\t1.0\n (0, 4)\t1.0"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,"(0, 0)\t1.0\n (0, 2)\t1.0"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,"(0, 0)\t1.0\n (0, 4)\t1.0"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,"(0, 0)\t1.0\n (0, 4)\t1.0"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,"(0, 1)\t1.0\n (0, 4)\t1.0"

In [10]:
# We need to extract the original categories for each encoded column
original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)}
# Manual creation of feature names
feature_names = []
for i, col in enumerate(cat_columns):
    for category in encoder.categories_[i]:
        feature_names.append(f"{col}_{category}")

encoded_df = pd.DataFrame(encoded_df, columns=feature_names)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,0
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,"(0, 1)\t1.0\n (0, 4)\t1.0"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,"(0, 0)\t1.0\n (0, 2)\t1.0"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,"(0, 0)\t1.0\n (0, 4)\t1.0"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,"(0, 0)\t1.0\n (0, 4)\t1.0"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,"(0, 1)\t1.0\n (0, 4)\t1.0"

---